//
// Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//

use objectscale_client::provisioning;
use pyo3::prelude::*;
use serde::Serialize;
use std::convert::From;

// Buckets are object containers that are used to control access to objects. ObjectScale supports bucket-to-bucket replication of the objects within a bucket.
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct Bucket {
    // Bucket name. Required.
    #[pyo3(set)]
    name: String,
    // Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
    id: String,
    // Hyperlink to the details for this resource
    link: ProvisioningLink,
    // Namespace. Required.
    #[pyo3(set)]
    namespace: String,
    //
    vpool: String,
    // "Locked" status of a bucket
    locked: bool,
    // flag indicating whether file-system is enabled for this bucket. is_object_lock_enabled and fs_access_enabled cannot be true at the same time. Default: false.
    #[pyo3(set)]
    fs_access_enabled: bool,
    // Bucket soft quota
    soft_quota: String,
    // Bucket creation time
    created: String,
    // Bucket isStaleAllowed flag. Default: false. Updatable
    #[pyo3(set)]
    is_stale_allowed: bool,
    // If true Object Lock and ADO can be enabled together. It cannot be changed once enabled. Default: false. Updatable
    #[pyo3(set)]
    is_object_lock_with_ado_allowed: bool,
    // Indicates the Retention mode for the specified object. is_object_lock_enabled and fs_access_enabled cannot be true at the same time. Can only set from false to true. Default: false. Updatable
    #[pyo3(set)]
    is_object_lock_enabled: bool,
    // Bucket is_tso_read_only flag. Can only be true if is_stale_allowed is true. Default: false.
    #[pyo3(set)]
    is_tso_read_only: bool,
    // Default object lock retention mode. Can be: GOVERNANCE or COMPLIANCE. Default: "". Updatable only when is_object_lock_enabled is true
    #[pyo3(set)]
    default_object_lock_retention_mode: String,
    // Default object lock retention years. Either Days or Years must be specified, but not both. Default: 0. Updatable only when is_object_lock_enabled is true
    #[pyo3(set)]
    default_object_lock_retention_years: i64,
    // Default object lock retention days. Either Days or Years must be specified, but not both. Default: 0. Updatable only when is_object_lock_enabled is true
    #[pyo3(set)]
    default_object_lock_retention_days: i64,
    // Default bucket retention
    default_retention: i64,
    // Default autocommit period in seconds. If fs_access_enabled is false, this value can't be updated. Default: 0. Updatable
    #[pyo3(set)]
    auto_commit_period: i64,
    // Block size in GB. Cannot be less than 1GB or use decimal values. Can be set to -1 to indicate quota value not defined. Default: -1. Updatable
    #[pyo3(set)]
    block_size: i64,
    // Notification size in GB. Cannot be less than 1GB or use decimal values. Can be set to -1 to indicate quota value not defined. Default: -1. Updatable
    #[pyo3(set)]
    notification_size: i64,
    // Block size in count. Default: -1.
    #[pyo3(set)]
    block_size_in_count: i64,
    // Notification size in count. Default: -1.
    #[pyo3(set)]
    notification_size_in_count: i64,
    // Bucket isEncryptionEnabled flag
    #[pyo3(set)]
    is_encryption_enabled: bool,
    // Default retention period in seconds. Should be less than maximum_fixed_retention. Default: 0. Updatable
    #[pyo3(set)]
    retention: i64,
    // Bucket's default group. Default: "". Updatable
    #[pyo3(set)]
    default_group: String,
    // Flag indicating the Read permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[pyo3(set)]
    default_group_file_read_permission: bool,
    // Flag indicating the file write permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[pyo3(set)]
    default_group_file_write_permission: bool,
    // Flag indicating the file execute permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[pyo3(set)]
    default_group_file_execute_permission: bool,
    // Flag indicating the directory read permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[pyo3(set)]
    default_group_dir_read_permission: bool,
    // Flag indicating the directory write permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[pyo3(set)]
    default_group_dir_write_permission: bool,
    // Flag indicating the directory execute permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[pyo3(set)]
    default_group_dir_execute_permission: bool,
    // default retention period setting. Default: see MinMaxGovernor. Updatable
    #[pyo3(set)]
    min_max_governor: MinMaxGovernor,
    // Bucket audit delete expiration in seconds. Default: -2. Updatable
    #[pyo3(set)]
    audit_delete_expiration: i64,
    // Enable advanced metadata search
    enable_advanced_metadata_search: bool,
    //
    advanced_metadata_search_target_name: String,
    //
    advanced_metadata_search_target_stream: String,
    // If true the bucket is in the process of being deleted. The bucket will be read only and no changes will be allowed on the bucket until the operation completes.
    is_empty_bucket_in_progress: bool,
    // versioning status for the bucket. Can be "" | Enabled | Suspended. It can be only "Enabled" when fs_access_enabled is false. During creation, it can be "" or "Enabled".Then it can switch between "Enabled" and "Suspended". Default: "". Updatable
    #[pyo3(set)]
    versioning_status: String,
    // Searchable tags assigned to objects created within the bucket. Default: see SearchMetaData. Updatable
    #[pyo3(set)]
    search_metadata: SearchMetaData,
    // Local object metadata reads bucket flag. Default: false. Updatable
    #[pyo3(set)]
    local_object_metadata_reads: bool,
    // API type
    api_type: String,
    // Bucket owner. If empty, it would be current user. Default: "". Updatable
    #[pyo3(set)]
    owner: String,
    // Keywords and labels that can be added by a user to a resource to make it easy to find when doing a search. Default: []. Updatable
    #[pyo3(set)]
    tags: Vec<BucketTag>,
}

impl From<provisioning::Bucket> for Bucket {
    fn from(bucket: provisioning::Bucket) -> Self {
        Self {
            name: bucket.name,
            id: bucket.id,
            link: ProvisioningLink::from(bucket.link),
            namespace: bucket.namespace,
            vpool: bucket.vpool,
            locked: bucket.locked,
            fs_access_enabled: bucket.fs_access_enabled,
            soft_quota: bucket.soft_quota,
            created: bucket.created,
            is_stale_allowed: bucket.is_stale_allowed,
            is_object_lock_with_ado_allowed: bucket.is_object_lock_with_ado_allowed,
            is_object_lock_enabled: bucket.is_object_lock_enabled,
            is_tso_read_only: bucket.is_tso_read_only,
            default_object_lock_retention_mode: bucket.default_object_lock_retention_mode,
            default_object_lock_retention_years: bucket.default_object_lock_retention_years,
            default_object_lock_retention_days: bucket.default_object_lock_retention_days,
            default_retention: bucket.default_retention,
            auto_commit_period: bucket.auto_commit_period,
            block_size: bucket.block_size,
            notification_size: bucket.notification_size,
            block_size_in_count: bucket.block_size_in_count,
            notification_size_in_count: bucket.notification_size_in_count,
            is_encryption_enabled: bucket.is_encryption_enabled,
            retention: bucket.retention,
            default_group: bucket.default_group,
            default_group_file_read_permission: bucket.default_group_file_read_permission,
            default_group_file_write_permission: bucket.default_group_file_write_permission,
            default_group_file_execute_permission: bucket.default_group_file_execute_permission,
            default_group_dir_read_permission: bucket.default_group_dir_read_permission,
            default_group_dir_write_permission: bucket.default_group_dir_write_permission,
            default_group_dir_execute_permission: bucket.default_group_dir_execute_permission,
            min_max_governor: MinMaxGovernor::from(bucket.min_max_governor),
            audit_delete_expiration: bucket.audit_delete_expiration,
            enable_advanced_metadata_search: bucket.enable_advanced_metadata_search,
            advanced_metadata_search_target_name: bucket.advanced_metadata_search_target_name,
            advanced_metadata_search_target_stream: bucket.advanced_metadata_search_target_stream,
            is_empty_bucket_in_progress: bucket.is_empty_bucket_in_progress,
            versioning_status: bucket.versioning_status,
            search_metadata: SearchMetaData::from(bucket.search_metadata),
            local_object_metadata_reads: bucket.local_object_metadata_reads,
            api_type: bucket.api_type,
            owner: bucket.owner,
            tags: bucket.tags.into_iter().map(BucketTag::from).collect(),
        }
    }
}

impl From<Bucket> for provisioning::Bucket {
    fn from(bucket: Bucket) -> Self {
        Self {
            name: bucket.name,
            id: bucket.id,
            link: provisioning::ProvisioningLink::from(bucket.link),
            namespace: bucket.namespace,
            vpool: bucket.vpool,
            locked: bucket.locked,
            fs_access_enabled: bucket.fs_access_enabled,
            soft_quota: bucket.soft_quota,
            created: bucket.created,
            is_stale_allowed: bucket.is_stale_allowed,
            is_object_lock_with_ado_allowed: bucket.is_object_lock_with_ado_allowed,
            is_object_lock_enabled: bucket.is_object_lock_enabled,
            is_tso_read_only: bucket.is_tso_read_only,
            default_object_lock_retention_mode: bucket.default_object_lock_retention_mode,
            default_object_lock_retention_years: bucket.default_object_lock_retention_years,
            default_object_lock_retention_days: bucket.default_object_lock_retention_days,
            default_retention: bucket.default_retention,
            auto_commit_period: bucket.auto_commit_period,
            block_size: bucket.block_size,
            notification_size: bucket.notification_size,
            block_size_in_count: bucket.block_size_in_count,
            notification_size_in_count: bucket.notification_size_in_count,
            is_encryption_enabled: bucket.is_encryption_enabled,
            retention: bucket.retention,
            default_group: bucket.default_group,
            default_group_file_read_permission: bucket.default_group_file_read_permission,
            default_group_file_write_permission: bucket.default_group_file_write_permission,
            default_group_file_execute_permission: bucket.default_group_file_execute_permission,
            default_group_dir_read_permission: bucket.default_group_dir_read_permission,
            default_group_dir_write_permission: bucket.default_group_dir_write_permission,
            default_group_dir_execute_permission: bucket.default_group_dir_execute_permission,
            min_max_governor: provisioning::MinMaxGovernor::from(bucket.min_max_governor),
            audit_delete_expiration: bucket.audit_delete_expiration,
            enable_advanced_metadata_search: bucket.enable_advanced_metadata_search,
            advanced_metadata_search_target_name: bucket.advanced_metadata_search_target_name,
            advanced_metadata_search_target_stream: bucket.advanced_metadata_search_target_stream,
            is_empty_bucket_in_progress: bucket.is_empty_bucket_in_progress,
            versioning_status: bucket.versioning_status,
            search_metadata: provisioning::SearchMetaData::from(bucket.search_metadata),
            local_object_metadata_reads: bucket.local_object_metadata_reads,
            api_type: bucket.api_type,
            owner: bucket.owner,
            tags: bucket
                .tags
                .into_iter()
                .map(provisioning::BucketTag::from)
                .collect(),
        }
    }
}

#[pymethods]
impl Bucket {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

// Lables for bucket.
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct BucketTag {
    // The key of a tag.
    #[pyo3(set)]
    key: String,
    // The value of a tag.
    #[pyo3(set)]
    value: String,
}

impl From<provisioning::BucketTag> for BucketTag {
    fn from(bucket_tag: provisioning::BucketTag) -> Self {
        Self {
            key: bucket_tag.key,
            value: bucket_tag.value,
        }
    }
}

impl From<BucketTag> for provisioning::BucketTag {
    fn from(bucket_tag: BucketTag) -> Self {
        Self {
            key: bucket_tag.key,
            value: bucket_tag.value,
        }
    }
}

#[pymethods]
impl BucketTag {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct MetaData {
    // The meta key type. Required
    #[pyo3(set)]
    datatype: String,
    // The meta key name. Required
    #[pyo3(set)]
    name: String,
    // The meta key data type. Required
    #[pyo3(set)]
    r#type: String,
}

impl From<provisioning::MetaData> for MetaData {
    fn from(meta_data: provisioning::MetaData) -> Self {
        Self {
            datatype: meta_data.datatype,
            name: meta_data.name,
            r#type: meta_data.r#type,
        }
    }
}

impl From<MetaData> for provisioning::MetaData {
    fn from(meta_data: MetaData) -> Self {
        Self {
            datatype: meta_data.datatype,
            name: meta_data.name,
            r#type: meta_data.r#type,
        }
    }
}

#[pymethods]
impl MetaData {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct MinMaxGovernor {
    // enforce retention: Default: false. Updatable
    #[pyo3(set)]
    enforce_retention: bool,
    // minimum fixed retention: Default: 0. Updatable
    #[pyo3(set)]
    minimum_fixed_retention: i64,
    // maximum fixed retention: Default: 0. Updatable
    #[pyo3(set)]
    maximum_fixed_retention: i64,
    // minimum variable retention: Default: 0. Updatable
    #[pyo3(set)]
    minimum_variable_retention: i64,
    // maximum variable retention: Default: 0. Updatable
    #[pyo3(set)]
    maximum_variable_retention: i64,
}

impl From<provisioning::MinMaxGovernor> for MinMaxGovernor {
    fn from(min_max_governor: provisioning::MinMaxGovernor) -> Self {
        Self {
            enforce_retention: min_max_governor.enforce_retention,
            minimum_fixed_retention: min_max_governor.minimum_fixed_retention,
            maximum_fixed_retention: min_max_governor.maximum_fixed_retention,
            minimum_variable_retention: min_max_governor.minimum_variable_retention,
            maximum_variable_retention: min_max_governor.maximum_variable_retention,
        }
    }
}

impl From<MinMaxGovernor> for provisioning::MinMaxGovernor {
    fn from(min_max_governor: MinMaxGovernor) -> Self {
        Self {
            enforce_retention: min_max_governor.enforce_retention,
            minimum_fixed_retention: min_max_governor.minimum_fixed_retention,
            maximum_fixed_retention: min_max_governor.maximum_fixed_retention,
            minimum_variable_retention: min_max_governor.minimum_variable_retention,
            maximum_variable_retention: min_max_governor.maximum_variable_retention,
        }
    }
}

#[pymethods]
impl MinMaxGovernor {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct ProvisioningLink {
    //
    #[pyo3(set)]
    rel: String,
    //
    #[pyo3(set)]
    href: String,
}

impl From<provisioning::ProvisioningLink> for ProvisioningLink {
    fn from(provisioning_link: provisioning::ProvisioningLink) -> Self {
        Self {
            rel: provisioning_link.rel,
            href: provisioning_link.href,
        }
    }
}

impl From<ProvisioningLink> for provisioning::ProvisioningLink {
    fn from(provisioning_link: ProvisioningLink) -> Self {
        Self {
            rel: provisioning_link.rel,
            href: provisioning_link.href,
        }
    }
}

#[pymethods]
impl ProvisioningLink {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct SearchMetaData {
    // Getter for the enabled flag. It cannot be re-enabled once disabled. Default: false. Updatable.
    #[pyo3(set)]
    is_enabled: bool,
    // Metadata list. Default: []
    #[pyo3(set)]
    metadata: Vec<MetaData>,
    // Getter for maxKeys.
    #[pyo3(set)]
    max_keys: i32,
    // Getter for the mdTokens flag.
    #[pyo3(set)]
    metadata_tokens: bool,
}

impl From<provisioning::SearchMetaData> for SearchMetaData {
    fn from(search_meta_data: provisioning::SearchMetaData) -> Self {
        Self {
            is_enabled: search_meta_data.is_enabled,
            metadata: search_meta_data
                .metadata
                .into_iter()
                .map(MetaData::from)
                .collect(),
            max_keys: search_meta_data.max_keys,
            metadata_tokens: search_meta_data.metadata_tokens,
        }
    }
}

impl From<SearchMetaData> for provisioning::SearchMetaData {
    fn from(search_meta_data: SearchMetaData) -> Self {
        Self {
            is_enabled: search_meta_data.is_enabled,
            metadata: search_meta_data
                .metadata
                .into_iter()
                .map(provisioning::MetaData::from)
                .collect(),
            max_keys: search_meta_data.max_keys,
            metadata_tokens: search_meta_data.metadata_tokens,
        }
    }
}

#[pymethods]
impl SearchMetaData {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

// Storage pool is a logical construct that contains physical nodes.
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct StoragePool {
    // Storage pool name. Required. Updatable
    #[pyo3(set)]
    name: String,
    // Storage pool id
    id: String,
    // Description. Default: "". Updatable
    #[pyo3(set)]
    description: String,
    // Flag indicating that storage pool is protected. Default: false
    #[pyo3(set)]
    is_protected: bool,
    // Flag indicating that cold storage encoding is enabled. Default: false
    #[pyo3(set)]
    is_cold_storage_enabled: bool,
    // Number of Data Blocks in EC Scheme
    number_of_data_blocks: i64,
    // Number of Code Blocks in EC Scheme
    number_of_code_blocks: i64,
    // Threshold percent at which warning alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Default: 30. Updatable
    #[pyo3(set)]
    warning_alert_at: i64,
    // Threshold percent at which error alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Default: 20. Updatable
    #[pyo3(set)]
    error_alert_at: i64,
    // Threshold percent at which critical alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Default: 15. Updatable
    #[pyo3(set)]
    critical_alert_at: i64,
    // Drive technology of VArray. Can be DRIVE_TECH_HDD. Required.
    #[pyo3(set)]
    label: String,
    // Drive technology of VArray. Can be HDD or NVMe. Required.
    #[pyo3(set)]
    drive_technology: String,
    // flag for status, -1 for null, 0 ~ 6 for value
    status: i64,
}

impl From<provisioning::StoragePool> for StoragePool {
    fn from(storage_pool: provisioning::StoragePool) -> Self {
        Self {
            name: storage_pool.name,
            id: storage_pool.id,
            description: storage_pool.description,
            is_protected: storage_pool.is_protected,
            is_cold_storage_enabled: storage_pool.is_cold_storage_enabled,
            number_of_data_blocks: storage_pool.number_of_data_blocks,
            number_of_code_blocks: storage_pool.number_of_code_blocks,
            warning_alert_at: storage_pool.warning_alert_at,
            error_alert_at: storage_pool.error_alert_at,
            critical_alert_at: storage_pool.critical_alert_at,
            label: storage_pool.label,
            drive_technology: storage_pool.drive_technology,
            status: storage_pool.status,
        }
    }
}

impl From<StoragePool> for provisioning::StoragePool {
    fn from(storage_pool: StoragePool) -> Self {
        Self {
            name: storage_pool.name,
            id: storage_pool.id,
            description: storage_pool.description,
            is_protected: storage_pool.is_protected,
            is_cold_storage_enabled: storage_pool.is_cold_storage_enabled,
            number_of_data_blocks: storage_pool.number_of_data_blocks,
            number_of_code_blocks: storage_pool.number_of_code_blocks,
            warning_alert_at: storage_pool.warning_alert_at,
            error_alert_at: storage_pool.error_alert_at,
            critical_alert_at: storage_pool.critical_alert_at,
            label: storage_pool.label,
            drive_technology: storage_pool.drive_technology,
            status: storage_pool.status,
        }
    }
}

#[pymethods]
impl StoragePool {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

// A VDC identifies the nodes that are participating in an ObjectScale instance.
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct Vdc {
    // Indicates whether the resource is global.
    global: bool,
    // Indicates whether the resource is remote.
    remote: bool,
    // Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier.
    name: String,
    // Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
    id: String,
    // Hyperlink to the details for this resource
    link: ProvisioningLink,
    // Timestamp that shows when this resource was created in ECS
    creation_time: String,
    // Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.
    inactive: bool,
    // Indicated whether the resource is an internal resource
    internal: bool,
    // VDC id
    vdc_id: String,
    // VDC name. Required. Updatable
    #[pyo3(set)]
    vdc_name: String,
    // VDC end points. Required. Updatable
    #[pyo3(set)]
    inter_vdc_endpoints: String,
    // VDC cmd end points. Required. Updatable
    #[pyo3(set)]
    inter_vdc_cmd_endpoints: String,
    // The management end points for the VDC. Required. Updatable
    #[pyo3(set)]
    management_endpoints: String,
    // Secret key for this VDC. Required. Updatable
    #[pyo3(set)]
    secret_keys: String,
    // True of vdc is permanently failed, false otherwise.
    permanently_failed: bool,
    // True of this vdc is local, false otherwise
    local: bool,
    // True of this vdc is hosted, false otherwise
    hosted: bool,
    // True of this vdc is enabled for encryption, false otherwise
    is_encryption_enabled: bool,
}

impl From<provisioning::Vdc> for Vdc {
    fn from(vdc: provisioning::Vdc) -> Self {
        Self {
            global: vdc.global,
            remote: vdc.remote,
            name: vdc.name,
            id: vdc.id,
            link: ProvisioningLink::from(vdc.link),
            creation_time: vdc.creation_time,
            inactive: vdc.inactive,
            internal: vdc.internal,
            vdc_id: vdc.vdc_id,
            vdc_name: vdc.vdc_name,
            inter_vdc_endpoints: vdc.inter_vdc_endpoints,
            inter_vdc_cmd_endpoints: vdc.inter_vdc_cmd_endpoints,
            management_endpoints: vdc.management_endpoints,
            secret_keys: vdc.secret_keys,
            permanently_failed: vdc.permanently_failed,
            local: vdc.local,
            hosted: vdc.hosted,
            is_encryption_enabled: vdc.is_encryption_enabled,
        }
    }
}

impl From<Vdc> for provisioning::Vdc {
    fn from(vdc: Vdc) -> Self {
        Self {
            global: vdc.global,
            remote: vdc.remote,
            name: vdc.name,
            id: vdc.id,
            link: provisioning::ProvisioningLink::from(vdc.link),
            creation_time: vdc.creation_time,
            inactive: vdc.inactive,
            internal: vdc.internal,
            vdc_id: vdc.vdc_id,
            vdc_name: vdc.vdc_name,
            inter_vdc_endpoints: vdc.inter_vdc_endpoints,
            inter_vdc_cmd_endpoints: vdc.inter_vdc_cmd_endpoints,
            management_endpoints: vdc.management_endpoints,
            secret_keys: vdc.secret_keys,
            permanently_failed: vdc.permanently_failed,
            local: vdc.local,
            hosted: vdc.hosted,
            is_encryption_enabled: vdc.is_encryption_enabled,
        }
    }
}

#[pymethods]
impl Vdc {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

// Vdc Keystore is to manage the certificates of a virtual data center (VDC)
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct VdcKeystore {
    // Keystore certificate chain in PEM format. Updatable
    #[pyo3(set)]
    chain: String,
    // The private key used to sign the certificate in PEM format. Updatable
    #[pyo3(set)]
    private_key: String,
}

impl From<provisioning::VdcKeystore> for VdcKeystore {
    fn from(vdc_keystore: provisioning::VdcKeystore) -> Self {
        Self {
            chain: vdc_keystore.chain,
            private_key: vdc_keystore.private_key,
        }
    }
}

impl From<VdcKeystore> for provisioning::VdcKeystore {
    fn from(vdc_keystore: VdcKeystore) -> Self {
        Self {
            chain: vdc_keystore.chain,
            private_key: vdc_keystore.private_key,
        }
    }
}

#[pymethods]
impl VdcKeystore {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}
