use objectscale_client::replication;
use pyo3::prelude::*;
use serde::Serialize;
use std::convert::From;

// Storage pool is a logical construct that contains physical nodes.
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct ReplicationGroup {
    // Indicates whether the resource is global.
    global: bool,
    // Indicates whether the resource is remote.
    remote: bool,
    // Varray mappings. Required
    #[pyo3(set)]
    varray_mappings: Vec<VarrayMapping>,
    // Unique name identifying this classification of replication group. Required. Updatable
    #[pyo3(set)]
    name: String,
    // Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
    id: String,
    // Timestamp that shows when this resource was created in ECS
    creation_time: i64,
    // Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.
    inactive: bool,
    // Indicated whether the resource is an internal resource
    internal: bool,
    // Description of the replication group. Default: "". Updatable
    #[pyo3(set)]
    description: String,
    // Parameter to check if the Vpool can access all Namespace. Default: true. Updatable
    #[pyo3(set)]
    is_allow_all_namespaces: bool,
    // Parameter to check if the rebalancing is enabled. Default: false. Updatable
    #[pyo3(set)]
    enable_rebalancing: bool,
    // Parameter to check if to use replication targets. Default: false
    #[pyo3(set)]
    use_replication_target: bool,
    // set full replication flag. Default: false
    #[pyo3(set)]
    is_full_rep: bool,
}

impl From<replication::ReplicationGroup> for ReplicationGroup {
    fn from(replication_group: replication::ReplicationGroup) -> Self {
        Self {
            global: replication_group.global,
            remote: replication_group.remote,
            varray_mappings: replication_group
                .varray_mappings
                .into_iter()
                .map(VarrayMapping::from)
                .collect(),
            name: replication_group.name,
            id: replication_group.id,
            creation_time: replication_group.creation_time,
            inactive: replication_group.inactive,
            internal: replication_group.internal,
            description: replication_group.description,
            is_allow_all_namespaces: replication_group.is_allow_all_namespaces,
            enable_rebalancing: replication_group.enable_rebalancing,
            use_replication_target: replication_group.use_replication_target,
            is_full_rep: replication_group.is_full_rep,
        }
    }
}

impl From<ReplicationGroup> for replication::ReplicationGroup {
    fn from(replication_group: ReplicationGroup) -> Self {
        Self {
            global: replication_group.global,
            remote: replication_group.remote,
            varray_mappings: replication_group
                .varray_mappings
                .into_iter()
                .map(replication::VarrayMapping::from)
                .collect(),
            name: replication_group.name,
            id: replication_group.id,
            creation_time: replication_group.creation_time,
            inactive: replication_group.inactive,
            internal: replication_group.internal,
            description: replication_group.description,
            is_allow_all_namespaces: replication_group.is_allow_all_namespaces,
            enable_rebalancing: replication_group.enable_rebalancing,
            use_replication_target: replication_group.use_replication_target,
            is_full_rep: replication_group.is_full_rep,
        }
    }
}

#[pymethods]
impl ReplicationGroup {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct VarrayMapping {
    // Virtual data center id
    #[pyo3(set)]
    name: String,
    // Storage pool id
    #[pyo3(set)]
    value: String,
    // is replication target
    #[pyo3(set)]
    is_replication_target: bool,
}

impl From<replication::VarrayMapping> for VarrayMapping {
    fn from(varray_mapping: replication::VarrayMapping) -> Self {
        Self {
            name: varray_mapping.name,
            value: varray_mapping.value,
            is_replication_target: varray_mapping.is_replication_target,
        }
    }
}

impl From<VarrayMapping> for replication::VarrayMapping {
    fn from(varray_mapping: VarrayMapping) -> Self {
        Self {
            name: varray_mapping.name,
            value: varray_mapping.value,
            is_replication_target: varray_mapping.is_replication_target,
        }
    }
}

#[pymethods]
impl VarrayMapping {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}
