use objectscale_client::tenancy;
use pyo3::prelude::*;
use serde::Serialize;
use std::convert::From;

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct Attribute {
    // Lookup string for this key-value pair
    #[pyo3(set)]
    key: String,
    // Lookup result for this key-value pair
    #[pyo3(set)]
    value: Vec<String>,
}

impl From<tenancy::Attribute> for Attribute {
    fn from(attribute: tenancy::Attribute) -> Self {
        Self {
            key: attribute.key,
            value: attribute.value,
        }
    }
}

impl From<Attribute> for tenancy::Attribute {
    fn from(attribute: Attribute) -> Self {
        Self {
            key: attribute.key,
            value: attribute.value,
        }
    }
}

#[pymethods]
impl Attribute {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

// ECS supports access by multiple tenants, where each tenant is defined by a namespace.
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct Namespace {
    // Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier. Required
    #[pyo3(set)]
    name: String,
    // Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time
    id: String,
    // Indicates whether the resource is global
    global: bool,
    // Indicates whether the resource is remote
    remote: bool,
    // Hyperlink to the details for this resource
    link: TenancyLink,
    // Timestamp that shows when this resource was created in ECS
    creation_time: i64,
    // Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database
    inactive: bool,
    // Indicated whether the resource is an internal resource
    internal: bool,
    // Default replication group identifier for this tenant when creating buckets. Required. Updatable
    #[pyo3(set)]
    default_data_services_vpool: String,
    // List of replication group that are allowed access to namespace.
    allowed_vpools_list: Vec<String>,
    // List of replication group that are not allowed access to namespace.
    disallowed_vpools_list: Vec<String>,
    // Comma separated list of namespace admins. Default: "". Updatable
    #[pyo3(set)]
    namespace_admins: String,
    // User Mapping. Default: []. Updatable
    #[pyo3(set)]
    user_mapping: Vec<UserMapping>,
    // encryption status of the namesapce. Default: false.
    #[pyo3(set)]
    is_encryption_enabled: bool,
    // Default bucket quota size. Default: -1. Updatable.
    #[pyo3(set)]
    default_bucket_block_size: i64,
    // List of groups from AD Server. Default: "". Updatable
    #[pyo3(set)]
    external_group_admins: String,
    // Namespace isStaleAllowed flag. Default: false. Updatable.
    #[pyo3(set)]
    is_stale_allowed: bool,
    // Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Default: false. Updatable
    #[pyo3(set)]
    is_object_lock_with_ado_allowed: bool,
    // Namespace isComplianceEnabled flag. Default: false.
    #[pyo3(set)]
    is_compliance_enabled: bool,
    // Notification Size in GB. Default: -1. Updatable.
    #[pyo3(set)]
    notification_size: i64,
    // Block Size in GB. Default: -1. Updatable.
    #[pyo3(set)]
    block_size: i64,
    // Notification Size in Count. Default: -1. Updatable.
    #[pyo3(set)]
    notification_size_in_count: i64,
    // Block Size in Count. Default: -1. Updatable.
    #[pyo3(set)]
    block_size_in_count: i64,
    // Default bucket audit delete expiration. Updatable
    default_audit_delete_expiration: i64,
    // retention classes. Default. Updatable
    #[pyo3(set)]
    retention_classes: RetionClasses,
    // root user name
    root_user_name: String,
    // root user password. Default: "".
    #[pyo3(set)]
    root_user_password: String,
}

impl From<tenancy::Namespace> for Namespace {
    fn from(namespace: tenancy::Namespace) -> Self {
        Self {
            name: namespace.name,
            id: namespace.id,
            global: namespace.global,
            remote: namespace.remote,
            link: TenancyLink::from(namespace.link),
            creation_time: namespace.creation_time,
            inactive: namespace.inactive,
            internal: namespace.internal,
            default_data_services_vpool: namespace.default_data_services_vpool,
            allowed_vpools_list: namespace.allowed_vpools_list,
            disallowed_vpools_list: namespace.disallowed_vpools_list,
            namespace_admins: namespace.namespace_admins,
            user_mapping: namespace
                .user_mapping
                .into_iter()
                .map(UserMapping::from)
                .collect(),
            is_encryption_enabled: namespace.is_encryption_enabled,
            default_bucket_block_size: namespace.default_bucket_block_size,
            external_group_admins: namespace.external_group_admins,
            is_stale_allowed: namespace.is_stale_allowed,
            is_object_lock_with_ado_allowed: namespace.is_object_lock_with_ado_allowed,
            is_compliance_enabled: namespace.is_compliance_enabled,
            notification_size: namespace.notification_size,
            block_size: namespace.block_size,
            notification_size_in_count: namespace.notification_size_in_count,
            block_size_in_count: namespace.block_size_in_count,
            default_audit_delete_expiration: namespace.default_audit_delete_expiration,
            retention_classes: RetionClasses::from(namespace.retention_classes),
            root_user_name: namespace.root_user_name,
            root_user_password: namespace.root_user_password,
        }
    }
}

impl From<Namespace> for tenancy::Namespace {
    fn from(namespace: Namespace) -> Self {
        Self {
            name: namespace.name,
            id: namespace.id,
            global: namespace.global,
            remote: namespace.remote,
            link: tenancy::TenancyLink::from(namespace.link),
            creation_time: namespace.creation_time,
            inactive: namespace.inactive,
            internal: namespace.internal,
            default_data_services_vpool: namespace.default_data_services_vpool,
            allowed_vpools_list: namespace.allowed_vpools_list,
            disallowed_vpools_list: namespace.disallowed_vpools_list,
            namespace_admins: namespace.namespace_admins,
            user_mapping: namespace
                .user_mapping
                .into_iter()
                .map(tenancy::UserMapping::from)
                .collect(),
            is_encryption_enabled: namespace.is_encryption_enabled,
            default_bucket_block_size: namespace.default_bucket_block_size,
            external_group_admins: namespace.external_group_admins,
            is_stale_allowed: namespace.is_stale_allowed,
            is_object_lock_with_ado_allowed: namespace.is_object_lock_with_ado_allowed,
            is_compliance_enabled: namespace.is_compliance_enabled,
            notification_size: namespace.notification_size,
            block_size: namespace.block_size,
            notification_size_in_count: namespace.notification_size_in_count,
            block_size_in_count: namespace.block_size_in_count,
            default_audit_delete_expiration: namespace.default_audit_delete_expiration,
            retention_classes: tenancy::RetionClasses::from(namespace.retention_classes),
            root_user_name: namespace.root_user_name,
            root_user_password: namespace.root_user_password,
        }
    }
}

#[pymethods]
impl Namespace {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct RetionClass {
    // Name of the retention class. Required. Updatable
    #[pyo3(set)]
    name: String,
    // Period of the retention class in seconds. Required. Updatable
    #[pyo3(set)]
    period: i64,
}

impl From<tenancy::RetionClass> for RetionClass {
    fn from(retion_class: tenancy::RetionClass) -> Self {
        Self {
            name: retion_class.name,
            period: retion_class.period,
        }
    }
}

impl From<RetionClass> for tenancy::RetionClass {
    fn from(retion_class: RetionClass) -> Self {
        Self {
            name: retion_class.name,
            period: retion_class.period,
        }
    }
}

#[pymethods]
impl RetionClass {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct RetionClasses {
    // Retention class, default: []. Updatable
    #[pyo3(set)]
    retention_class: Vec<RetionClass>,
}

impl From<tenancy::RetionClasses> for RetionClasses {
    fn from(retion_classes: tenancy::RetionClasses) -> Self {
        Self {
            retention_class: retion_classes
                .retention_class
                .into_iter()
                .map(RetionClass::from)
                .collect(),
        }
    }
}

impl From<RetionClasses> for tenancy::RetionClasses {
    fn from(retion_classes: RetionClasses) -> Self {
        Self {
            retention_class: retion_classes
                .retention_class
                .into_iter()
                .map(tenancy::RetionClass::from)
                .collect(),
        }
    }
}

#[pymethods]
impl RetionClasses {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct TenancyLink {
    //
    #[pyo3(set)]
    rel: String,
    //
    #[pyo3(set)]
    href: String,
}

impl From<tenancy::TenancyLink> for TenancyLink {
    fn from(tenancy_link: tenancy::TenancyLink) -> Self {
        Self {
            rel: tenancy_link.rel,
            href: tenancy_link.href,
        }
    }
}

impl From<TenancyLink> for tenancy::TenancyLink {
    fn from(tenancy_link: TenancyLink) -> Self {
        Self {
            rel: tenancy_link.rel,
            href: tenancy_link.href,
        }
    }
}

#[pymethods]
impl TenancyLink {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}

//
#[derive(Clone, Debug, Default, Serialize)]
#[pyclass(get_all)]
pub(crate) struct UserMapping {
    // A single-valued attribute indicating the user's IDP domain
    #[pyo3(set)]
    domain: String,
    // Attributes
    #[pyo3(set)]
    attributes: Vec<Attribute>,
    // Groups
    #[pyo3(set)]
    groups: Vec<String>,
}

impl From<tenancy::UserMapping> for UserMapping {
    fn from(user_mapping: tenancy::UserMapping) -> Self {
        Self {
            domain: user_mapping.domain,
            attributes: user_mapping
                .attributes
                .into_iter()
                .map(Attribute::from)
                .collect(),
            groups: user_mapping.groups,
        }
    }
}

impl From<UserMapping> for tenancy::UserMapping {
    fn from(user_mapping: UserMapping) -> Self {
        Self {
            domain: user_mapping.domain,
            attributes: user_mapping
                .attributes
                .into_iter()
                .map(tenancy::Attribute::from)
                .collect(),
            groups: user_mapping.groups,
        }
    }
}

#[pymethods]
impl UserMapping {
    #[new]
    fn new() -> Self {
        Self::default()
    }

    fn __str__(&self) -> String {
        format!("{}", serde_json::to_string(self).unwrap())
    }
}
