//
// Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//

#ifndef OBJECTSCALE_CLIENT_H
#define OBJECTSCALE_CLIENT_H

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ManagementClient manages ObjectScale resources with the ObjectScale management REST APIs.
 */
typedef struct ManagementClient ManagementClient;

typedef struct RCString {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} RCString;

/**
 * Build a new ManagementClient.
 *
 */
struct ManagementClient *new_management_client(struct RCString endpoint,
                                               struct RCString username,
                                               struct RCString password,
                                               bool insecure,
                                               struct RCString *err);

void destroy_management_client(struct ManagementClient *management_client);

/**
 * Creates a new IAM User.
 *
 * user: IAM User to create
 *
 */
struct RCString management_client_create_user(struct ManagementClient *management_client,
                                              struct RCString user,
                                              struct RCString *err);

/**
 * Retrieve IAM user.
 *
 * name: The name of the user to retrieve.
 * namespace: ECS namespace IAM entity belongs to
 *
 */
struct RCString management_client_get_user(struct ManagementClient *management_client,
                                           struct RCString name,
                                           struct RCString namespace_,
                                           struct RCString *err);

/**
 * Updates an IAM user.
 *
 * user: IAM User to be updated
 *
 */
bool management_client_update_user(struct ManagementClient *management_client,
                                   struct RCString user,
                                   struct RCString *err);

/**
 * Delete specified IAM User.
 *
 * user_name: The name of the user to delete. Cannot be empty.
 * namespace: Namespace of the user(id of the account the user belongs to). Cannot be empty.
 *
 */
void management_client_delete_user(struct ManagementClient *management_client,
                                   struct RCString user_name,
                                   struct RCString namespace_,
                                   struct RCString *err);

/**
 * Lists the IAM users.
 *
 * namespace: Namespace of users(id of the account the user belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_users(struct ManagementClient *management_client,
                                             struct RCString namespace_,
                                             struct RCString *err);

/**
 * Attaches the specified managed policy to the specified user.
 *
 * user_policy_attachment: UserPolicyAttachment to create
 *
 * PS: attach the same policy would throw error
 *
 */
struct RCString management_client_create_user_policy_attachment(struct ManagementClient *management_client,
                                                                struct RCString user_policy_attachment,
                                                                struct RCString *err);

/**
 * Remove the specified managed policy attached to the specified user.
 *
 * user_policy_attachment: UserPolicyAttachment to delete.
 *
 */
void management_client_delete_user_policy_attachment(struct ManagementClient *management_client,
                                                     struct RCString user_policy_attachment,
                                                     struct RCString *err);

/**
 * Lists all managed policies that are attached to the specified IAM user.
 *
 * user_name: The name of the user to list attached policies for. Cannot be empty.
 * namespace: Namespace of the user(id of the account the user belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_user_policy_attachments(struct ManagementClient *management_client,
                                                               struct RCString user_name,
                                                               struct RCString namespace_,
                                                               struct RCString *err);

/**
 * Creates AccessKey for user.
 *
 * access_key: AccessKey to create
 *
 */
struct RCString management_client_create_access_key(struct ManagementClient *management_client,
                                                    struct RCString access_key,
                                                    struct RCString *err);

/**
 * Updates AccessKey for user.
 *
 * access_key: AccessKey to update
 *
 */
bool management_client_update_access_key(struct ManagementClient *management_client,
                                         struct RCString access_key,
                                         struct RCString *err);

/**
 * Deletes the access key pair associated with the specified IAM user.
 *
 * access_key_id: The ID of the access key you want to delete. Cannot be empty.
 * user_name: Name of the user to delete accesskeys. Cannot be empty.
 * namespace: Namespace of the access key(id of the account the access key belongs to). Cannot be empty.
 *
 */
void management_client_delete_access_key(struct ManagementClient *management_client,
                                         struct RCString access_key_id,
                                         struct RCString user_name,
                                         struct RCString namespace_,
                                         struct RCString *err);

/**
 * Returns information about the access key IDs associated with the specified IAM user.
 *
 * user_name: Name of the user to list accesskeys. Cannot be empty.
 * namespace: Namespace of the access key(id of the account the access key belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_access_keys(struct ManagementClient *management_client,
                                                   struct RCString user_name,
                                                   struct RCString namespace_,
                                                   struct RCString *err);

/**
 * Create a new Managed Policy.
 *
 * policy: IAM Policy to create
 *
 */
struct RCString management_client_create_policy(struct ManagementClient *management_client,
                                                struct RCString policy,
                                                struct RCString *err);

/**
 * Retrieve information about the specified Managed Policy.
 *
 * policy_arn: Arn of the policy to retrieve. Cannot be empty.
 * namespace: Namespace of the policy(id of the account the policy belongs to). Cannot be empty.
 *
 */
struct RCString management_client_get_policy(struct ManagementClient *management_client,
                                             struct RCString policy_arn,
                                             struct RCString namespace_,
                                             struct RCString *err);

/**
 * Create a new version of the specified managed policy.
 *
 * policy_arn: Arn of the policy to retrieve. Cannot be empty.
 * namespace: Namespace of the policy(id of the account the policy belongs to). Cannot be empty.
 *
 */
bool management_client_update_policy(struct ManagementClient *management_client,
                                     struct RCString policy,
                                     struct RCString *err);

/**
 * Delete the specified Managed Policy.
 *
 * policy_arn: Arn of the policy to delete. Cannot be empty.
 * namespace: Namespace of the policy(id of the account the policy belongs to). Cannot be empty.
 *
 */
void management_client_delete_policy(struct ManagementClient *management_client,
                                     struct RCString policy_arn,
                                     struct RCString namespace_,
                                     struct RCString *err);

/**
 * Lists IAM Managed Policies.
 *
 * namespace: Namespace of the policies(id of the account policies belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_policies(struct ManagementClient *management_client,
                                                struct RCString namespace_,
                                                struct RCString *err);

/**
 * Creates a new IAM Group.
 *
 * group: IAM Group to create
 *
 */
struct RCString management_client_create_group(struct ManagementClient *management_client,
                                               struct RCString group,
                                               struct RCString *err);

/**
 * Returns the information about the specified IAM Group.
 *
 * group_name: The name of the group to retrieve. Cannot be empty.
 * namespace: Namespace of the group(id of the account the group belongs to). Cannot be empty.
 *
 */
struct RCString management_client_get_group(struct ManagementClient *management_client,
                                            struct RCString group_name,
                                            struct RCString namespace_,
                                            struct RCString *err);

/**
 * Delete specified IAM User.
 *
 * group_name: The name of the group to delete. Cannot be empty.
 * namespace: Namespace of the group(id of the account the group belongs to). Cannot be empty.
 *
 */
void management_client_delete_group(struct ManagementClient *management_client,
                                    struct RCString group_name,
                                    struct RCString namespace_,
                                    struct RCString *err);

/**
 * Lists the IAM groups.
 *
 * namespace: Namespace of groups(id of the account groups belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_groups(struct ManagementClient *management_client,
                                              struct RCString namespace_,
                                              struct RCString *err);

/**
 * Attaches the specified managed policy to the specified group.
 *
 * group_policy_attachment: GroupPolicyAttachment to create
 *
 */
struct RCString management_client_create_group_policy_attachment(struct ManagementClient *management_client,
                                                                 struct RCString group_policy_attachment,
                                                                 struct RCString *err);

/**
 * Remove the specified managed policy attached to the specified group.
 *
 * group_policy_attachment: GroupPolicyAttachment to delete.
 *
 */
void management_client_delete_group_policy_attachment(struct ManagementClient *management_client,
                                                      struct RCString group_policy_attachment,
                                                      struct RCString *err);

/**
 * Lists all managed policies that are attached to the specified IAM Group.
 *
 * group_name: The name of the group to list attached policies for. Cannot be empty.
 * namespace: Namespace of the group(id of the account the group belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_group_policy_attachments(struct ManagementClient *management_client,
                                                                struct RCString group_name,
                                                                struct RCString namespace_,
                                                                struct RCString *err);

/**
 * Creates a new IAM Role.
 *
 * role: IAM Role to create
 *
 */
struct RCString management_client_create_role(struct ManagementClient *management_client,
                                              struct RCString role,
                                              struct RCString *err);

/**
 * Returns the information about the specified IAM Role.
 *
 * role_name: The name of the role to retrieve. Cannot be empty.
 * namespace: Namespace of the role(id of the account the role belongs to). Cannot be empty.
 *
 */
struct RCString management_client_get_role(struct ManagementClient *management_client,
                                           struct RCString role_name,
                                           struct RCString namespace_,
                                           struct RCString *err);

/**
 * Updates a new IAM Role.
 *
 * role: IAM Role to update
 *
 */
bool management_client_update_role(struct ManagementClient *management_client,
                                   struct RCString role,
                                   struct RCString *err);

/**
 * Delete specified IAM Role.
 *
 * role_name: The name of the role to delete. Cannot be empty.
 * namespace: Namespace of the role(id of the account the role belongs to). Cannot be empty.
 *
 */
void management_client_delete_role(struct ManagementClient *management_client,
                                   struct RCString role_name,
                                   struct RCString namespace_,
                                   struct RCString *err);

/**
 * Lists the IAM roles.
 *
 * namespace: Namespace of roles(id of the account roles belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_roles(struct ManagementClient *management_client,
                                             struct RCString namespace_,
                                             struct RCString *err);

/**
 * Attaches the specified managed policy to the specified role.
 *
 * role_policy_attachment: RolePolicyAttachment to create
 *
 */
struct RCString management_client_create_role_policy_attachment(struct ManagementClient *management_client,
                                                                struct RCString role_policy_attachment,
                                                                struct RCString *err);

/**
 * Remove the specified managed policy attached to the specified role.
 *
 * role_policy_attachment: RolePolicyAttachment to delete.
 *
 */
void management_client_delete_role_policy_attachment(struct ManagementClient *management_client,
                                                     struct RCString role_policy_attachment,
                                                     struct RCString *err);

/**
 * Lists all managed policies that are attached to the specified IAM Role.
 *
 * role_name: The name of the role to list attached policies for. Cannot be empty.
 * namespace: Namespace of the role(id of the account the role belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_role_policy_attachments(struct ManagementClient *management_client,
                                                               struct RCString role_name,
                                                               struct RCString namespace_,
                                                               struct RCString *err);

/**
 * Lists all IAM users, groups, and roles that the specified managed policy is attached to.
 *
 * policy_arn: Arn of the policy to list entities for. Cannot be empty.
 * namespace: Namespace of the policy(id of the account the policy belongs to). Cannot be empty.
 * entity_filter: The entity type to use for filtering the results. Valid values: User, Role, Group.
 * usage_filter: The policy usage method to use for filtering the results. Valid values: PermissionsPolicy, PermissionsBoundary.
 *
 */
struct RCString management_client_get_entities_for_policy(struct ManagementClient *management_client,
                                                          struct RCString policy_arn,
                                                          struct RCString namespace_,
                                                          struct RCString entity_filter,
                                                          struct RCString usage_filter,
                                                          struct RCString *err);

/**
 * Adds the specified user to the specified group.
 *
 * user_group_membership: UserGroupMembership to create.
 *
 */
struct RCString management_client_create_user_group_membership(struct ManagementClient *management_client,
                                                               struct RCString user_group_membership,
                                                               struct RCString *err);

/**
 * Removes the specified user from the specified group.
 *
 * user_group_membership: GroupPolicyAttachment to delete.
 *
 */
void management_client_delete_user_group_membership(struct ManagementClient *management_client,
                                                    struct RCString user_group_membership,
                                                    struct RCString *err);

/**
 * Lists the IAM groups that the specified IAM user belongs to.
 *
 * user_name: The name of the user to list group membership for. Cannot be empty.
 * namespace: Namespace of the user(id of the account the user belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_user_group_memberships_by_user(struct ManagementClient *management_client,
                                                                      struct RCString user_name,
                                                                      struct RCString namespace_,
                                                                      struct RCString *err);

/**
 * Create SAML Identity Provider
 *
 * provider: SAML provider to create
 *
 */
struct RCString management_client_create_saml_provider(struct ManagementClient *management_client,
                                                       struct RCString provider,
                                                       struct RCString *err);

/**
 * Retrieve the SAML IdP document.
 *
 * arn: The name of the provider to retrieve.
 * namespace: Namespace of the role(id of the account the role belongs to). Cannot be empty.
 *
 */
struct RCString management_client_get_saml_provider(struct ManagementClient *management_client,
                                                    struct RCString arn,
                                                    struct RCString namespace_,
                                                    struct RCString *err);

/**
 * Update the SAML Identity Provider.
 *
 * role: SAML Identity Provider to update
 *
 */
bool management_client_update_saml_provider(struct ManagementClient *management_client,
                                            struct RCString provider,
                                            struct RCString *err);

/**
 * Delete the SAML Identity Provider.
 *
 * arn: The ARN of the provider to delete.
 * namespace: ECS namespace IAM entity belongs to
 *
 */
void management_client_delete_saml_provider(struct ManagementClient *management_client,
                                            struct RCString arn,
                                            struct RCString namespace_,
                                            struct RCString *err);

/**
 * List the SAML Identity Providers.
 *
 * namespace: ECS namespace IAM entity belongs to
 *
 */
struct RCString management_client_list_saml_providers(struct ManagementClient *management_client,
                                                      struct RCString namespace_,
                                                      struct RCString *err);

/**
 * Lists the IAM users that the specified IAM group contains.
 *
 * group_name: The name of the group to list contained users for. Cannot be empty.
 * namespace: Namespace of the group(id of the account the group belongs to). Cannot be empty.
 *
 */
struct RCString management_client_list_user_group_memberships_by_group(struct ManagementClient *management_client,
                                                                       struct RCString group_name,
                                                                       struct RCString namespace_,
                                                                       struct RCString *err);

/**
 * Gets the list of buckets for the specified namespace.
 *
 * namespace: Namespace for which buckets should be listed. Cannot be empty.
 * name_prefix: Case sensitive prefix of the Bucket name with a wild card(*). Can be empty or any_prefix_string*.
 *
 */
struct RCString management_client_list_buckets(struct ManagementClient *management_client,
                                               struct RCString namespace_,
                                               struct RCString name_prefix,
                                               struct RCString *err);

/**
 * Create an bucket.
 *
 * bucket: Bucket to create.
 *
 */
struct RCString management_client_create_bucket(struct ManagementClient *management_client,
                                                struct RCString bucket,
                                                struct RCString *err);

/**
 * Gets bucket information for the specified bucket.
 *
 * name: Bucket name for which information will be retrieved. Cannot be empty.
 * namespace: Namespace associated. Cannot be empty.
 *
 */
struct RCString management_client_get_bucket(struct ManagementClient *management_client,
                                             struct RCString name,
                                             struct RCString namespace_,
                                             struct RCString *err);

/**
 * Update an bucket.
 *
 * bucket: Bucket to update.
 *
 */
bool management_client_update_bucket(struct ManagementClient *management_client,
                                     struct RCString bucket,
                                     struct RCString *err);

/**
 * Deletes the specified bucket.
 *
 * name: Bucket name to be deleted. Cannot be empty.
 * namespace: Namespace associated. Cannot be empty.
 * emptyBucket: If true, the contents of the bucket will be emptied as part of the delete, otherwise it will fail if the bucket is not empty.
 *
 */
void management_client_delete_bucket(struct ManagementClient *management_client,
                                     struct RCString name,
                                     struct RCString namespace_,
                                     bool empty_bucket,
                                     struct RCString *err);

/**
 * Creates a namespace with the given details.
 *
 * namespace: Namespace to create
 *
 */
struct RCString management_client_create_namespace(struct ManagementClient *management_client,
                                                   struct RCString namespace_,
                                                   struct RCString *err);

/**
 * Gets the details for the given namespace.
 *
 * id: Namespace identifier for which details needs to be retrieved.
 *
 */
struct RCString management_client_get_namespace(struct ManagementClient *management_client,
                                                struct RCString id,
                                                struct RCString *err);

/**
 * Update a namespace with the given details.
 *
 * namespace: Namespace to be updated
 *
 */
bool management_client_update_namespace(struct ManagementClient *management_client,
                                        struct RCString namespace_,
                                        struct RCString *err);

/**
 * Deactivates and deletes the given namespace and all associated user mappings.
 *
 * id: An active namespace identifier which needs to be deactivated/deleted
 *
 */
void management_client_delete_namespace(struct ManagementClient *management_client,
                                        struct RCString id,
                                        struct RCString *err);

/**
 * Gets the list of all configured namespaces.
 *
 * name_prefix: Case sensitive prefix of the Namespace name with a wild card(*) Ex : any_prefix_string*.
 *
 */
struct RCString management_client_list_namespaces(struct ManagementClient *management_client,
                                                  struct RCString name_prefix,
                                                  struct RCString *err);

/**
 * Creates local users for the VDC.
 *
 * user: ManagementUser to create
 *
 */
struct RCString management_client_create_management_user(struct ManagementClient *management_client,
                                                         struct RCString user,
                                                         struct RCString *err);

/**
 * Gets details for the specified local management user.
 *
 * id: User identifier for which local user information needs to be retrieved
 *
 */
struct RCString management_client_get_management_user(struct ManagementClient *management_client,
                                                      struct RCString id,
                                                      struct RCString *err);

/**
 * Updates user details for the specified local management user.
 *
 * user: ManagementUser to be updated
 *
 */
bool management_client_update_management_user(struct ManagementClient *management_client,
                                              struct RCString user,
                                              struct RCString *err);

/**
 * Deletes local management user information for the specified user identifier.
 *
 * id: User identifier for which local user information needs to be deleted.
 *
 */
void management_client_delete_management_user(struct ManagementClient *management_client,
                                              struct RCString id,
                                              struct RCString *err);

/**
 * Gets all configured local management users.
 *
 */
struct RCString management_client_list_management_users(struct ManagementClient *management_client,
                                                        struct RCString *err);

/**
 * Creates a user for a specified namespace.
 *
 * user: ObjectUser to create
 *
 */
struct RCString management_client_create_object_user(struct ManagementClient *management_client,
                                                     struct RCString user,
                                                     struct RCString *err);

/**
 * Gets user details for the specified user belong to the specified namespace.
 *
 * name: Valid user identifier
 * namespace: The namespace to which user belong
 *
 */
struct RCString management_client_get_object_user(struct ManagementClient *management_client,
                                                  struct RCString name,
                                                  struct RCString namespace_,
                                                  struct RCString *err);

/**
 * Updates user details for the specified object user.
 *
 * user: ObjectUser to be updated
 *
 */
bool management_client_update_object_user(struct ManagementClient *management_client,
                                          struct RCString user,
                                          struct RCString *err);

/**
 * Deletes the specified user and its secret keys.
 *
 * name: User to be deleted.
 * namespace: Namespace identifier to associate with the user
 *
 */
void management_client_delete_object_user(struct ManagementClient *management_client,
                                          struct RCString name,
                                          struct RCString namespace_,
                                          struct RCString *err);

/**
 * Gets identifiers for all configured users.
 *
 */
struct RCString management_client_list_object_users(struct ManagementClient *management_client,
                                                    struct RCString *err);

/**
 * Get the certificate chain being used by ECS
 *
 */
struct RCString management_client_get_vdc_keystore(struct ManagementClient *management_client,
                                                   struct RCString *err);

/**
 * Set the certificate chain being used by ECS.
 *
 * keystore: VdcKeystore to be updated
 *
 */
bool management_client_update_vdc_keystore(struct ManagementClient *management_client,
                                           struct RCString keystore,
                                           struct RCString *err);

/**
 * Create a VDC with the specified details.
 *
 * vdc: VDC to be created
 *
 */
struct RCString management_client_create_vdc(struct ManagementClient *management_client,
                                             struct RCString vdc,
                                             struct RCString *err);

/**
 * Gets the details for a VDC the identify of which is specified by its name.
 *
 * name: VDC name for which VDC Information is to be retrieved
 *
 */
struct RCString management_client_get_vdc(struct ManagementClient *management_client,
                                          struct RCString name,
                                          struct RCString *err);

/**
 * Update VDC info
 *
 * vdc: VDC to be updated
 *
 */
bool management_client_update_vdc(struct ManagementClient *management_client,
                                  struct RCString vdc,
                                  struct RCString *err);

/**
 * Deactivates and deletes a VDC.
 *
 * id: VDC identifier for which VDC Information needs to be deleted
 *
 */
void management_client_delete_vdc(struct ManagementClient *management_client,
                                  struct RCString id,
                                  struct RCString *err);

/**
 * Gets all details of all configured VDCs.
 *
 */
struct RCString management_client_list_vdcs(struct ManagementClient *management_client,
                                            struct RCString *err);

/**
 * Create a storage pool with the specified details.
 *
 * sp: Storage pool to be created
 *
 */
struct RCString management_client_create_storage_pool(struct ManagementClient *management_client,
                                                      struct RCString sp,
                                                      struct RCString *err);

/**
 * Gets the details for the specified storage pool.
 *
 * id: Storage pool identifier to be retrieved
 *
 */
struct RCString management_client_get_storage_pool(struct ManagementClient *management_client,
                                                   struct RCString id,
                                                   struct RCString *err);

/**
 * Updates storage pool for the specified identifier..
 *
 * sp: Storage pool to be updated
 *
 */
bool management_client_update_storage_pool(struct ManagementClient *management_client,
                                           struct RCString sp,
                                           struct RCString *err);

/**
 * Gets a list of storage pools from the local VDC.
 *
 */
struct RCString management_client_list_storage_pools(struct ManagementClient *management_client,
                                                     struct RCString *err);

/**
 * Creates a replication group that includes the specified storage pools
 *
 * rg: ReplicationGroup to create
 *
 */
struct RCString management_client_create_replication_group(struct ManagementClient *management_client,
                                                           struct RCString rg,
                                                           struct RCString *err);

/**
 * Gets the details for the specified replication group.
 *
 * id: Replication group identifier for which details needs to be retrieved
 *
 */
struct RCString management_client_get_replication_group(struct ManagementClient *management_client,
                                                        struct RCString id,
                                                        struct RCString *err);

/**
 * Updates the name and description for a replication group.
 *
 * rg: Replication group which details needs to be updated
 *
 */
bool management_client_update_replication_group(struct ManagementClient *management_client,
                                                struct RCString rg,
                                                struct RCString *err);

/**
 * Lists all configured replication groups.
 *
 */
struct RCString management_client_list_replication_groups(struct ManagementClient *management_client,
                                                          struct RCString *err);

void free_rcstring(struct RCString rcstring);

#endif /* OBJECTSCALE_CLIENT_H */
