/* Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved. */

#ifndef OBJECTSCALE_CLIENT_H
#define OBJECTSCALE_CLIENT_H

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Client Client;

typedef struct RCString {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} RCString;

struct Client *new_client(struct RCString endpoint,
                          struct RCString username,
                          struct RCString password,
                          bool insecure,
                          struct RCString *err);

void destroy_client(struct Client *client);

struct RCString client_create_account(struct Client *client,
                                      struct RCString caccount,
                                      struct RCString *err);

struct RCString client_get_account(struct Client *client,
                                   struct RCString account_id,
                                   struct RCString *err);

void client_delete_account(struct Client *client, struct RCString account_id, struct RCString *err);

struct RCString client_list_accounts(struct Client *client, struct RCString *err);

void free_rcstring(struct RCString rcstring);

#endif /* OBJECTSCALE_CLIENT_H */
