package pkg

// #include "objectscale_client.h"
import "C"

// Buckets are object containers that are used to control access to objects. ObjectScale supports bucket-to-bucket replication of the objects within a bucket.
type Bucket struct {
	// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier.
	Name string `attr:"name"`
	// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
	Id string `attr:"id"`
	// Hyperlink to the details for this resource
	Link Link `attr:"link"`
	// Namespace
	Namespace string `attr:"namespace"`
	//
	Vpool string `attr:"vpool"`
	// "Locked" status of a bucket
	Locked bool `attr:"locked"`
	// Bucket "file system access enabled" status
	FsAccessEnabled bool `attr:"fs_access_enabled"`
	// Bucket soft quota
	SoftQuota string `attr:"soft_quota"`
	// Bucket creation time
	Created string `attr:"created"`
	// Bucket isStaleAllowed flag
	IsStaleAllowed bool `attr:"is_stale_allowed"`
	// If true Object Lock and ADO can be enabled together. See the Admin Guide for more information.
	IsObjectLockWithAdoAllowed bool `attr:"is_object_lock_with_ado_allowed"`
	//
	IsObjectLockEnabled bool `attr:"is_object_lock_enabled"`
	// Bucket isStaleAllowed flag
	IsTsoReadOnly bool `attr:"is_tso_read_only"`
	// Default object lock retention mode
	DefaultObjectLockRetentionMode string `attr:"default_object_lock_retention_mode"`
	// Default object lock retention years
	DefaultObjectLockRetentionYears int32 `attr:"default_object_lock_retention_years"`
	// Default object lock retention days
	DefaultObjectLockRetentionDays int32 `attr:"default_object_lock_retention_days"`
	// Default bucket retention
	DefaultRetention int64 `attr:"default_retention"`
	// Block size in GB
	BlockSize int64 `attr:"block_size"`
	// auto-commit interval
	AutoCommitPeriod int64 `attr:"auto_commit_period"`
	// Notification size in GB
	NotificationSize int64 `attr:"notification_size"`
	// Block size in count
	BlockSizeInCount int64 `attr:"block_size_in_count"`
	// Notification size in count
	NotificationSizeInCount int64 `attr:"notification_size_in_count"`
	// Bucket isEncryptionEnabled flag
	IsEncryptionEnabled bool `attr:"is_encryption_enabled"`
	// Default retention value for the bucket.
	Retention int64 `attr:"retention"`
	// Bucket's default group
	DefaultGroup string `attr:"default_group"`
	// Flag indicating the Read permission for default group
	DefaultGroupFileReadPermission bool `attr:"default_group_file_read_permission"`
	// Flag indicating the file write permission for default group
	DefaultGroupFileWritePermission bool `attr:"default_group_file_write_permission"`
	// Flag indicating the file execute permission for default group
	DefaultGroupFileExecutePermission bool `attr:"default_group_file_execute_permission"`
	// Flag indicating the directory read permission for default group. This is only applicable to folders created within the Filesystem-Enabled bucket. It is not applicable to files/objects
	DefaultGroupDirReadPermission bool `attr:"default_group_dir_read_permission"`
	// Flag indicating the directory write permission for default group. This is only applicable to folders created within the Filesystem-Enabled bucket. It is not applicable to files/objects
	DefaultGroupDirWritePermission bool `attr:"default_group_dir_write_permission"`
	// Flag indicating the directory execute permission for default group. This is only applicable to folders created within the Filesystem-Enabled bucket. It is not applicable to files/objects
	DefaultGroupDirExecutePermission bool `attr:"default_group_dir_execute_permission"`
	//
	MinMaxGovernor MinMaxGovernor `attr:"min_max_governor"`
	// Bucket audit delete expiration in seconds
	AuditDeleteExpiration int64 `attr:"audit_delete_expiration"`
	// Enable advanced metadata search
	EnableAdvancedMetadataSearch bool `attr:"enable_advanced_metadata_search"`
	//
	AdvancedMetadataSearchTargetName string `attr:"advanced_metadata_search_target_name"`
	//
	AdvancedMetadataSearchTargetStream string `attr:"advanced_metadata_search_target_stream"`
	// Optional. If true the bucket is in the process of being deleted. The bucket will be read only and no changes will be allowed on the bucket until the operation completes.
	IsEmptyBucketInProgress bool `attr:"is_empty_bucket_in_progress"`
	//
	VersioningStatus string `attr:"versioning_status"`
	//
	SearchMetadata SearchMetaData `attr:"search_metadata"`
	// Local object metadata reads bucket flag.
	LocalObjectMetadataReads bool `attr:"local_object_metadata_reads"`
	// API type
	ApiType string `attr:"api_type"`
	// Bucket owner
	Owner string `attr:"owner"`
	// Keywords and labels that can be added by a user to a resource to make it easy to find when doing a search.
	Tags []BucketTag `attr:"tags" json:"TagSet"`
}

// Lables for bucket.
type BucketTag struct {
	// The key of a tag.
	Key string `attr:"key"`
	// The value of a tag.
	Value string `attr:"value"`
}

type Link struct {
	//
	Rel string `attr:"rel" yaml:"rel" json:"rel"`
	//
	Href string `attr:"href" yaml:"href" json:"href"`
}

type MetaData struct {
	// The meta key type
	Datatype string `attr:"datatype" yaml:"datatype" json:"datatype"`
	// The meta key name
	Name string `attr:"name" yaml:"name" json:"name"`
	// The meta key data type
	Type string `attr:"type" yaml:"type" json:"type"`
}

type MinMaxGovernor struct {
	//
	EnforceRetention bool `attr:"enforce_retention"`
	//
	MinimumFixedRetention int64 `attr:"minimum_fixed_retention"`
	//
	MaximumFixedRetention int64 `attr:"maximum_fixed_retention"`
	//
	MinimumVariableRetention int64 `attr:"minimum_variable_retention"`
	//
	MaximumVariableRetention int64 `attr:"maximum_variable_retention"`
}

type SearchMetaData struct {
	// Getter for the enabled flag.
	IsEnabled bool `attr:"is_enabled" yaml:"is_enabled" json:"isEnabled"`
	//
	Metadata []MetaData `attr:"metadata" yaml:"metadata" json:"metadata"`
	// Getter for maxKeys.
	MaxKeys int32 `attr:"max_keys" yaml:"max_keys" json:"maxKeys"`
	// Getter for the mdTokens flag.
	MetadataTokens bool `attr:"metadata_tokens" yaml:"metadata_tokens" json:"metadataTokens"`
}
