/* Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved. */

#ifndef OBJECTSCALE_CLIENT_H
#define OBJECTSCALE_CLIENT_H

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Client Client;

typedef struct RCString {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} RCString;

typedef struct CTag {
  struct RCString key;
  struct RCString value;
} CTag;

typedef struct RCArray_CTag {
  struct CTag *ptr;
  uintptr_t len;
  uintptr_t cap;
} RCArray_CTag;

typedef struct CAccount {
  struct RCString account_id;
  struct RCString objscale;
  struct RCString create_date;
  bool encryption_enabled;
  bool account_disabled;
  struct RCString alias;
  struct RCString description;
  bool protection_enabled;
  struct RCString tso_id;
  struct RCArray_CTag tags;
} CAccount;

typedef struct RCArray_CAccount {
  struct CAccount *ptr;
  uintptr_t len;
  uintptr_t cap;
} RCArray_CAccount;

struct Client *new_client(struct RCString endpoint,
                          struct RCString username,
                          struct RCString password,
                          bool insecure,
                          struct RCString *err);

void destroy_client(struct Client *client);

struct CAccount *client_create_account(struct Client *client,
                                       const struct CAccount *caccount,
                                       struct RCString *err);

struct CAccount *client_get_account(struct Client *client,
                                    struct RCString account_id,
                                    struct RCString *err);

void client_delete_account(struct Client *client, struct RCString account_id, struct RCString *err);

struct RCArray_CAccount client_list_accounts(struct Client *client, struct RCString *err);

void destroy_caccount(struct CAccount *caccount);

void free_rcarray_caccount(struct RCArray_CAccount rcarray);

void destroy_ctag(struct CTag *ctag);

void free_rcarray_ctag(struct RCArray_CTag rcarray);

void free_rcstring(struct RCString rcstring);

#endif /* OBJECTSCALE_CLIENT_H */
