package pkg

// #include "objectscale_client.h"
import "C"

// Buckets are object containers that are used to control access to objects. ObjectScale supports bucket-to-bucket replication of the objects within a bucket.
type Bucket struct {
	// Bucket name. Required.
	Name string `json:"name" yaml:"name" tf:"name"`
	// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
	Id string `json:"id" yaml:"id" tf:"id"`
	// Hyperlink to the details for this resource
	Link ProvisioningLink `json:"link" yaml:"link" tf:"link"`
	// Namespace. Required.
	Namespace string `json:"namespace" yaml:"namespace" tf:"namespace"`
	//
	Vpool string `json:"vpool" yaml:"vpool" tf:"vpool"`
	// "Locked" status of a bucket
	Locked bool `json:"locked" yaml:"locked" tf:"locked"`
	// flag indicating whether file-system is enabled for this bucket. is_object_lock_enabled and fs_access_enabled cannot be true at the same time. Default: false.
	FsAccessEnabled bool `json:"fs_access_enabled" yaml:"filesystem_enabled" tf:"fs_access_enabled"`
	// Bucket soft quota
	SoftQuota string `json:"softquota" yaml:"softquota" tf:"soft_quota"`
	// Bucket creation time
	Created string `json:"created" yaml:"created" tf:"created"`
	// Bucket isStaleAllowed flag. Default: false. Updatable
	IsStaleAllowed bool `json:"is_stale_allowed" yaml:"is_stale_allowed" tf:"is_stale_allowed"`
	// If true Object Lock and ADO can be enabled together. It cannot be changed once enabled. Default: false. Updatable
	IsObjectLockWithAdoAllowed bool `json:"is_object_lock_with_ado_allowed" yaml:"is_object_lock_with_ado_allowed" tf:"is_object_lock_with_ado_allowed"`
	// Indicates the Retention mode for the specified object. is_object_lock_enabled and fs_access_enabled cannot be true at the same time. Can only set from false to true. Default: false. Updatable
	IsObjectLockEnabled bool `json:"is_object_lock_enabled" yaml:"is_object_lock_enabled" tf:"is_object_lock_enabled"`
	// Bucket is_tso_read_only flag. Can only be true if is_stale_allowed is true. Default: false.
	IsTsoReadOnly bool `json:"is_tso_read_only" yaml:"is_tso_read_only" tf:"is_tso_read_only"`
	// Default object lock retention mode. Can be: GOVERNANCE or COMPLIANCE. Default: "". Updatable only when is_object_lock_enabled is true
	DefaultObjectLockRetentionMode string `json:"default_object_lock_retention_mode" yaml:"default_object_lock_retention_mode" tf:"default_object_lock_retention_mode"`
	// Default object lock retention years. Either Days or Years must be specified, but not both. Default: 0. Updatable only when is_object_lock_enabled is true
	DefaultObjectLockRetentionYears int64 `json:"default_object_lock_retention_years" yaml:"default_object_lock_retention_years" tf:"default_object_lock_retention_years"`
	// Default object lock retention days. Either Days or Years must be specified, but not both. Default: 0. Updatable only when is_object_lock_enabled is true
	DefaultObjectLockRetentionDays int64 `json:"default_object_lock_retention_days" yaml:"default_object_lock_retention_days" tf:"default_object_lock_retention_days"`
	// Default bucket retention
	DefaultRetention int64 `json:"default_retention" yaml:"default_retention" tf:"default_retention"`
	// Default autocommit period in seconds. If fs_access_enabled is false, this value can't be updated. Default: 0. Updatable
	AutoCommitPeriod int64 `json:"auto_commit_period" yaml:"autocommit_period" tf:"auto_commit_period"`
	// Block size in GB. Cannot be less than 1GB or use decimal values. Can be set to -1 to indicate quota value not defined. Default: -1. Updatable
	BlockSize int64 `json:"block_size" yaml:"blockSize" tf:"block_size"`
	// Notification size in GB. Cannot be less than 1GB or use decimal values. Can be set to -1 to indicate quota value not defined. Default: -1. Updatable
	NotificationSize int64 `json:"notification_size" yaml:"notificationSize" tf:"notification_size"`
	// Block size in count. Default: -1.
	BlockSizeInCount int64 `json:"blockSizeInCount" yaml:"blockSizeInCount" tf:"block_size_in_count"`
	// Notification size in count. Default: -1.
	NotificationSizeInCount int64 `json:"notificationSizeInCount" yaml:"notificationSizeInCount" tf:"notification_size_in_count"`
	// Bucket isEncryptionEnabled flag
	IsEncryptionEnabled bool `json:"is_encryption_enabled" yaml:"is_encryption_enabled" tf:"is_encryption_enabled"`
	// Default retention period in seconds. Should be less than maximum_fixed_retention. Default: 0. Updatable
	Retention int64 `json:"retention" yaml:"retention" tf:"retention"`
	// Bucket's default group. Default: "". Updatable
	DefaultGroup string `json:"default_group" yaml:"default_group" tf:"default_group"`
	// Flag indicating the Read permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
	DefaultGroupFileReadPermission bool `json:"default_group_file_read_permission" yaml:"default_group_file_read_permission" tf:"default_group_file_read_permission"`
	// Flag indicating the file write permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
	DefaultGroupFileWritePermission bool `json:"default_group_file_write_permission" yaml:"default_group_file_write_permission" tf:"default_group_file_write_permission"`
	// Flag indicating the file execute permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
	DefaultGroupFileExecutePermission bool `json:"default_group_file_execute_permission" yaml:"default_group_file_execute_permission" tf:"default_group_file_execute_permission"`
	// Flag indicating the directory read permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
	DefaultGroupDirReadPermission bool `json:"default_group_dir_read_permission" yaml:"default_group_dir_read_permission" tf:"default_group_dir_read_permission"`
	// Flag indicating the directory write permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
	DefaultGroupDirWritePermission bool `json:"default_group_dir_write_permission" yaml:"default_group_dir_write_permission" tf:"default_group_dir_write_permission"`
	// Flag indicating the directory execute permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
	DefaultGroupDirExecutePermission bool `json:"default_group_dir_execute_permission" yaml:"default_group_dir_execute_permission" tf:"default_group_dir_execute_permission"`
	// default retention period setting. Default: see MinMaxGovernor. Updatable
	MinMaxGovernor MinMaxGovernor `json:"min_max_governor" yaml:"min_max_governor" tf:"min_max_governor"`
	// Bucket audit delete expiration in seconds. Default: -2. Updatable
	AuditDeleteExpiration int64 `json:"audit_delete_expiration" yaml:"audit_delete_expiration" tf:"audit_delete_expiration"`
	// Enable advanced metadata search
	EnableAdvancedMetadataSearch bool `json:"enableAdvancedMetadataSearch" yaml:"enableAdvancedMetadataSearch" tf:"enable_advanced_metadata_search"`
	//
	AdvancedMetadataSearchTargetName string `json:"advancedMetadataSearchTargetName" yaml:"advancedMetadataSearchTargetName" tf:"advanced_metadata_search_target_name"`
	//
	AdvancedMetadataSearchTargetStream string `json:"advancedMetadataSearchTargetStream" yaml:"advancedMetadataSearchTargetStream" tf:"advanced_metadata_search_target_stream"`
	// If true the bucket is in the process of being deleted. The bucket will be read only and no changes will be allowed on the bucket until the operation completes.
	IsEmptyBucketInProgress bool `json:"is_empty_bucket_in_progress" yaml:"is_empty_bucket_in_progress" tf:"is_empty_bucket_in_progress"`
	// versioning status for the bucket. Can be "" | Enabled | Suspended. It can be only "Enabled" when fs_access_enabled is false. During creation, it can be "" or "Enabled".Then it can switch between "Enabled" and "Suspended". Default: "". Updatable
	VersioningStatus string `json:"versioning_status" yaml:"versioning_status" tf:"versioning_status"`
	// Searchable tags assigned to objects created within the bucket. Default: see SearchMetaData. Updatable
	SearchMetadata SearchMetaData `json:"search_metadata" yaml:"search_metadata" tf:"search_metadata"`
	// Local object metadata reads bucket flag. Default: false. Updatable
	LocalObjectMetadataReads bool `json:"local_object_metadata_reads" yaml:"local_object_metadata_reads" tf:"local_object_metadata_reads"`
	// API type
	ApiType string `json:"api_type" yaml:"api_type" tf:"api_type"`
	// Bucket owner. If empty, it would be current user. Default: "". Updatable
	Owner string `json:"owner" yaml:"owner" tf:"owner"`
	// Keywords and labels that can be added by a user to a resource to make it easy to find when doing a search. Default: []. Updatable
	Tags []BucketTag `json:"TagSet" yaml:"TagSet" tf:"tags"`
}

// Lables for bucket.
type BucketTag struct {
	// The key of a tag.
	Key string `json:"Key" yaml:"Key" tf:"key"`
	// The value of a tag.
	Value string `json:"Value" yaml:"Value" tf:"value"`
}

type MetaData struct {
	// The meta key type. Required
	Datatype string `json:"datatype" yaml:"datatype" tf:"datatype"`
	// The meta key name. Required
	Name string `json:"name" yaml:"name" tf:"name"`
	// The meta key data type. Required
	Type string `json:"type" yaml:"type" tf:"type"`
}

type MinMaxGovernor struct {
	// enforce retention: Default: false. Updatable
	EnforceRetention bool `json:"enforce_retention" yaml:"enforce_retention" tf:"enforce_retention"`
	// minimum fixed retention: Default: 0. Updatable
	MinimumFixedRetention int64 `json:"minimum_fixed_retention" yaml:"minimum_fixed_retention" tf:"minimum_fixed_retention"`
	// maximum fixed retention: Default: 0. Updatable
	MaximumFixedRetention int64 `json:"maximum_fixed_retention" yaml:"maximum_fixed_retention" tf:"maximum_fixed_retention"`
	// minimum variable retention: Default: 0. Updatable
	MinimumVariableRetention int64 `json:"minimum_variable_retention" yaml:"minimum_variable_retention" tf:"minimum_variable_retention"`
	// maximum variable retention: Default: 0. Updatable
	MaximumVariableRetention int64 `json:"maximum_variable_retention" yaml:"maximum_variable_retention" tf:"maximum_variable_retention"`
}

type ProvisioningLink struct {
	//
	Rel string `json:"rel" yaml:"rel" tf:"rel"`
	//
	Href string `json:"href" yaml:"href" tf:"href"`
}

type SearchMetaData struct {
	// Getter for the enabled flag. It cannot be re-enabled once disabled. Default: false. Updatable.
	IsEnabled bool `json:"isEnabled" yaml:"is_enabled" tf:"is_enabled"`
	// Metadata list. Default: []
	Metadata []MetaData `json:"metadata" yaml:"metadata" tf:"metadata"`
	// Getter for maxKeys.
	MaxKeys int32 `json:"maxKeys" yaml:"max_keys" tf:"max_keys"`
	// Getter for the mdTokens flag.
	MetadataTokens bool `json:"metadata_tokens" yaml:"metadata_tokens" tf:"metadata_tokens"`
}

// Storage pool is a logical construct that contains physical nodes.
type StoragePool struct {
	// Storage pool name. Required. Updatable
	Name string `json:"name" yaml:"name" tf:"name"`
	// Storage pool id
	Id string `json:"id" yaml:"id" tf:"id"`
	// Description. Default: "". Updatable
	Description string `json:"description" yaml:"description" tf:"description"`
	// Flag indicating that storage pool is protected. Default: false
	IsProtected bool `json:"isProtected" yaml:"isProtected" tf:"is_protected"`
	// Flag indicating that cold storage encoding is enabled. Default: false
	IsColdStorageEnabled bool `json:"isColdStorageEnabled" yaml:"isColdStorageEnabled" tf:"is_cold_storage_enabled"`
	// Number of Data Blocks in EC Scheme
	NumberOfDataBlocks int64 `json:"numberOfDataBlocks" yaml:"numberOfDataBlocks" tf:"number_of_data_blocks"`
	// Number of Code Blocks in EC Scheme
	NumberOfCodeBlocks int64 `json:"numberOfCodeBlocks" yaml:"numberOfCodeBlocks" tf:"number_of_code_blocks"`
	// Threshold percent at which warning alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Default: 30. Updatable
	WarningAlertAt int64 `json:"warningAlertAt" yaml:"warningAlertAt" tf:"warning_alert_at"`
	// Threshold percent at which error alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Default: 20. Updatable
	ErrorAlertAt int64 `json:"errorAlertAt" yaml:"errorAlertAt" tf:"error_alert_at"`
	// Threshold percent at which critical alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Default: 15. Updatable
	CriticalAlertAt int64 `json:"criticalAlertAt" yaml:"criticalAlertAt" tf:"critical_alert_at"`
	// Drive technology of VArray. Can be DRIVE_TECH_HDD. Required.
	Label string `json:"label" yaml:"label" tf:"label"`
	// Drive technology of VArray. Can be HDD or NVMe. Required.
	DriveTechnology string `json:"driveTechnology" yaml:"driveTechnology" tf:"drive_technology"`
	// flag for status, -1 for null, 0 ~ 6 for value
	Status int64 `json:"status" yaml:"status" tf:"status"`
}

// A VDC identifies the nodes that are participating in an ObjectScale instance.
type Vdc struct {
	// Indicates whether the resource is global.
	Global bool `json:"global" yaml:"global" tf:"global"`
	// Indicates whether the resource is remote.
	Remote bool `json:"remote" yaml:"remote" tf:"remote"`
	// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier.
	Name string `json:"name" yaml:"name" tf:"name"`
	// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
	Id string `json:"id" yaml:"id" tf:"id"`
	// Hyperlink to the details for this resource
	Link ProvisioningLink `json:"link" yaml:"link" tf:"link"`
	// Timestamp that shows when this resource was created in ECS
	CreationTime string `json:"creation_time" yaml:"creation_time" tf:"creation_time"`
	// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.
	Inactive bool `json:"inactive" yaml:"inactive" tf:"inactive"`
	// Indicated whether the resource is an internal resource
	Internal bool `json:"internal" yaml:"internal" tf:"internal"`
	// VDC id
	VdcId string `json:"vdcId" yaml:"vdcId" tf:"vdc_id"`
	// VDC name. Required. Updatable
	VdcName string `json:"vdcName" yaml:"vdcName" tf:"vdc_name"`
	// VDC end points. Required. Updatable
	InterVdcEndpoints string `json:"interVdcEndPoints" yaml:"interVdcEndPoints" tf:"inter_vdc_endpoints"`
	// VDC cmd end points. Required. Updatable
	InterVdcCmdEndpoints string `json:"interVdcCmdEndPoints" yaml:"interVdcCmdEndPoints" tf:"inter_vdc_cmd_endpoints"`
	// The management end points for the VDC. Required. Updatable
	ManagementEndpoints string `json:"managementEndPoints" yaml:"managementEndPoints" tf:"management_endpoints"`
	// Secret key for this VDC. Required. Updatable
	SecretKeys string `json:"secretKeys" yaml:"secretKeys" tf:"secret_keys"`
	// True of vdc is permanently failed, false otherwise.
	PermanentlyFailed bool `json:"permanentlyFailed" yaml:"permanentlyFailed" tf:"permanently_failed"`
	// True of this vdc is local, false otherwise
	Local bool `json:"local" yaml:"local" tf:"local"`
	// True of this vdc is hosted, false otherwise
	Hosted bool `json:"hosted" yaml:"hosted" tf:"hosted"`
	// True of this vdc is enabled for encryption, false otherwise
	IsEncryptionEnabled bool `json:"is_encryption_enabled" yaml:"is_encryption_enabled" tf:"is_encryption_enabled"`
}

// Vdc Keystore is to manage the certificates of a virtual data center (VDC)
type VdcKeystore struct {
	// Keystore certificate chain in PEM format. Updatable
	Chain string `json:"chain" yaml:"chain" tf:"chain"`
	// The private key used to sign the certificate in PEM format. Updatable
	PrivateKey string `json:"private_key" yaml:"private_key" tf:"private_key"`
}
