package pkg

// #include "objectscale_client.h"
import "C"

// Buckets are object containers that are used to control access to objects. ObjectScale supports bucket-to-bucket replication of the objects within a bucket.
type Bucket struct {
	// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier. Required.
	Name string `json:"name" yaml:"name"`
	// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
	Id string `json:"id" yaml:"id"`
	// Hyperlink to the details for this resource
	Link ProvisioningLink `json:"link" yaml:"link"`
	// Namespace. Required.
	Namespace string `json:"namespace" yaml:"namespace"`
	//
	Vpool string `json:"vpool" yaml:"vpool"`
	// "Locked" status of a bucket
	Locked bool `json:"locked" yaml:"locked"`
	// Bucket "file system access enabled" status
	FsAccessEnabled bool `json:"fs_access_enabled" yaml:"fs_access_enabled"`
	// Bucket soft quota
	SoftQuota string `json:"softquota" yaml:"softquota"`
	// Bucket creation time
	Created string `json:"created" yaml:"created"`
	// Bucket isStaleAllowed flag
	IsStaleAllowed bool `json:"is_stale_allowed" yaml:"is_stale_allowed"`
	// If true Object Lock and ADO can be enabled together. See the Admin Guide for more information.
	IsObjectLockWithAdoAllowed bool `json:"is_object_lock_with_ado_allowed" yaml:"is_object_lock_with_ado_allowed"`
	//
	IsObjectLockEnabled bool `json:"is_object_lock_enabled" yaml:"is_object_lock_enabled"`
	// Bucket isStaleAllowed flag
	IsTsoReadOnly bool `json:"is_tso_read_only" yaml:"is_tso_read_only"`
	// Default object lock retention mode
	DefaultObjectLockRetentionMode string `json:"default_object_lock_retention_mode" yaml:"default_object_lock_retention_mode"`
	// Default object lock retention years
	DefaultObjectLockRetentionYears int32 `json:"default_object_lock_retention_years" yaml:"default_object_lock_retention_years"`
	// Default object lock retention days
	DefaultObjectLockRetentionDays int32 `json:"default_object_lock_retention_days" yaml:"default_object_lock_retention_days"`
	// Default bucket retention
	DefaultRetention int64 `json:"default_retention" yaml:"default_retention"`
	// Block size in GB
	BlockSize int64 `json:"block_size" yaml:"block_size"`
	// auto-commit interval
	AutoCommitPeriod int64 `json:"auto_commit_period" yaml:"auto_commit_period"`
	// Notification size in GB
	NotificationSize int64 `json:"notification_size" yaml:"notification_size"`
	// Block size in count
	BlockSizeInCount int64 `json:"blockSizeInCount" yaml:"blockSizeInCount"`
	// Notification size in count
	NotificationSizeInCount int64 `json:"notificationSizeInCount" yaml:"notificationSizeInCount"`
	// Bucket isEncryptionEnabled flag
	IsEncryptionEnabled bool `json:"is_encryption_enabled" yaml:"is_encryption_enabled"`
	// Default retention value for the bucket.
	Retention int64 `json:"retention" yaml:"retention"`
	// Bucket's default group
	DefaultGroup string `json:"default_group" yaml:"default_group"`
	// Flag indicating the Read permission for default group
	DefaultGroupFileReadPermission bool `json:"default_group_file_read_permission" yaml:"default_group_file_read_permission"`
	// Flag indicating the file write permission for default group
	DefaultGroupFileWritePermission bool `json:"default_group_file_write_permission" yaml:"default_group_file_write_permission"`
	// Flag indicating the file execute permission for default group
	DefaultGroupFileExecutePermission bool `json:"default_group_file_execute_permission" yaml:"default_group_file_execute_permission"`
	// Flag indicating the directory read permission for default group. This is only applicable to folders created within the Filesystem-Enabled bucket. It is not applicable to files/objects
	DefaultGroupDirReadPermission bool `json:"default_group_dir_read_permission" yaml:"default_group_dir_read_permission"`
	// Flag indicating the directory write permission for default group. This is only applicable to folders created within the Filesystem-Enabled bucket. It is not applicable to files/objects
	DefaultGroupDirWritePermission bool `json:"default_group_dir_write_permission" yaml:"default_group_dir_write_permission"`
	// Flag indicating the directory execute permission for default group. This is only applicable to folders created within the Filesystem-Enabled bucket. It is not applicable to files/objects
	DefaultGroupDirExecutePermission bool `json:"default_group_dir_execute_permission" yaml:"default_group_dir_execute_permission"`
	//
	MinMaxGovernor MinMaxGovernor `json:"min_max_governor" yaml:"min_max_governor"`
	// Bucket audit delete expiration in seconds
	AuditDeleteExpiration int64 `json:"audit_delete_expiration" yaml:"audit_delete_expiration"`
	// Enable advanced metadata search
	EnableAdvancedMetadataSearch bool `json:"enableAdvancedMetadataSearch" yaml:"enableAdvancedMetadataSearch"`
	//
	AdvancedMetadataSearchTargetName string `json:"advancedMetadataSearchTargetName" yaml:"advancedMetadataSearchTargetName"`
	//
	AdvancedMetadataSearchTargetStream string `json:"advancedMetadataSearchTargetStream" yaml:"advancedMetadataSearchTargetStream"`
	// Optional. If true the bucket is in the process of being deleted. The bucket will be read only and no changes will be allowed on the bucket until the operation completes.
	IsEmptyBucketInProgress bool `json:"is_empty_bucket_in_progress" yaml:"is_empty_bucket_in_progress"`
	//
	VersioningStatus string `json:"versioning_status" yaml:"versioning_status"`
	// Searchable tags assigned to objects created within the bucket.
	SearchMetadata SearchMetaData `json:"search_metadata" yaml:"search_metadata"`
	// Local object metadata reads bucket flag.
	LocalObjectMetadataReads bool `json:"local_object_metadata_reads" yaml:"local_object_metadata_reads"`
	// API type
	ApiType string `json:"api_type" yaml:"api_type"`
	// Bucket owner. Updatable
	Owner string `json:"owner" yaml:"owner"`
	// Keywords and labels that can be added by a user to a resource to make it easy to find when doing a search. Updatable
	Tags []BucketTag `json:"TagSet" yaml:"TagSet"`
}

// Lables for bucket.
type BucketTag struct {
	// The key of a tag.
	Key string `json:"Key" yaml:"Key"`
	// The value of a tag.
	Value string `json:"Value" yaml:"Value"`
}

type MetaData struct {
	// The meta key type
	Datatype string `json:"datatype" yaml:"datatype"`
	// The meta key name
	Name string `json:"name" yaml:"name"`
	// The meta key data type
	Type string `json:"type" yaml:"type"`
}

type MinMaxGovernor struct {
	//
	EnforceRetention bool `json:"enforce_retention" yaml:"enforce_retention"`
	//
	MinimumFixedRetention int64 `json:"minimum_fixed_retention" yaml:"minimum_fixed_retention"`
	//
	MaximumFixedRetention int64 `json:"maximum_fixed_retention" yaml:"maximum_fixed_retention"`
	//
	MinimumVariableRetention int64 `json:"minimum_variable_retention" yaml:"minimum_variable_retention"`
	//
	MaximumVariableRetention int64 `json:"maximum_variable_retention" yaml:"maximum_variable_retention"`
}

type ProvisioningLink struct {
	//
	Rel string `json:"rel" yaml:"rel"`
	//
	Href string `json:"href" yaml:"href"`
}

type SearchMetaData struct {
	// Getter for the enabled flag.
	IsEnabled bool `json:"isEnabled" yaml:"is_enabled"`
	//
	Metadata []MetaData `json:"metadata" yaml:"metadata"`
	// Getter for maxKeys.
	MaxKeys int32 `json:"maxKeys" yaml:"max_keys"`
	// Getter for the mdTokens flag.
	MetadataTokens bool `json:"metadata_tokens" yaml:"metadata_tokens"`
}

// Storage pool is a logical construct that contains physical nodes.
type StoragePool struct {
	// Storage pool name. Updatable
	Name string `json:"name" yaml:"name"`
	// Storage pool id
	Id string `json:"id" yaml:"id"`
	// Description. Updatable
	Description string `json:"description" yaml:"description"`
	// Flag indicating that storage pool is protected
	IsProtected bool `json:"isProtected" yaml:"isProtected"`
	// Flag indicating that cold storage encoding is enabled
	IsColdStorageEnabled bool `json:"isColdStorageEnabled" yaml:"isColdStorageEnabled"`
	// Number of Data Blocks in EC Scheme
	NumberOfDataBlocks int64 `json:"numberOfDataBlocks" yaml:"numberOfDataBlocks"`
	// Number of Code Blocks in EC Scheme
	NumberOfCodeBlocks int64 `json:"numberOfCodeBlocks" yaml:"numberOfCodeBlocks"`
	// Threshold percent at which warning alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Updatable
	WarningAlertAt int64 `json:"warningAlertAt" yaml:"warningAlertAt"`
	// Threshold percent at which error alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Updatable
	ErrorAlertAt int64 `json:"errorAlertAt" yaml:"errorAlertAt"`
	// Threshold percent at which critical alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Updatable
	CriticalAlertAt int64 `json:"criticalAlertAt" yaml:"criticalAlertAt"`
	// Drive technology of VArray
	Label string `json:"label" yaml:"label"`
	// Drive technology of VArray
	DriveTechnology string `json:"driveTechnology" yaml:"driveTechnology"`
	// flag for status, -1 for null, 0 ~ 6 for value
	Status int64 `json:"status" yaml:"status"`
}

// A VDC identifies the nodes that are participating in an ObjectScale instance.
type Vdc struct {
	// Indicates whether the resource is global.
	Global bool `json:"global" yaml:"global"`
	// Indicates whether the resource is remote.
	Remote bool `json:"remote" yaml:"remote"`
	// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier.
	Name string `json:"name" yaml:"name"`
	// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
	Id string `json:"id" yaml:"id"`
	// Hyperlink to the details for this resource
	Link ProvisioningLink `json:"link" yaml:"link"`
	// Timestamp that shows when this resource was created in ECS
	CreationTime string `json:"creation_time" yaml:"creation_time"`
	// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.
	Inactive bool `json:"inactive" yaml:"inactive"`
	// Indicated whether the resource is an internal resource
	Internal bool `json:"internal" yaml:"internal"`
	// VDC id
	VdcId string `json:"vdcId" yaml:"vdcId"`
	// VDC name
	VdcName string `json:"vdcName" yaml:"vdcName"`
	// VDC end points
	InterVdcEndpoints string `json:"interVdcEndPoints" yaml:"interVdcEndPoints"`
	// VDC cmd end points
	InterVdcCmdEndpoints string `json:"interVdcCmdEndPoints" yaml:"interVdcCmdEndPoints"`
	// The management end points for the VDC
	ManagementEndpoints string `json:"managementEndPoints" yaml:"managementEndPoints"`
	// Secret key for this VDC
	SecretKeys string `json:"secretKeys" yaml:"secretKeys"`
	// True of vdc is permanently failed, false otherwise.
	PermanentlyFailed bool `json:"permanentlyFailed" yaml:"permanentlyFailed"`
	// True of this vdc is local, false otherwise
	Local bool `json:"local" yaml:"local"`
	// True of this vdc is hosted, false otherwise
	Hosted bool `json:"hosted" yaml:"hosted"`
	// True of this vdc is enabled for encryption, false otherwise
	IsEncryptionEnabled bool `json:"is_encryption_enabled" yaml:"is_encryption_enabled"`
}

// Vdc Keystore is to manage the certificates of a virtual data center (VDC)
type VdcKeystore struct {
	// Keystore certificate chain in PEM format
	Chain string `json:"chain" yaml:"chain"`
	// The private key used to sign the certificate in PEM format.
	PrivateKey string `json:"private_key" yaml:"private_key"`
}
