package pkg

// #include "objectscale_client.h"
import "C"

// Storage pool is a logical construct that contains physical nodes.
type ReplicationGroup struct {
	// Indicates whether the resource is global.
	Global bool `json:"global" yaml:"global" tf:"global"`
	// Indicates whether the resource is remote.
	Remote bool `json:"remote" yaml:"remote" tf:"remote"`
	// Varray mappings. Required
	VarrayMappings []VarrayMapping `json:"varrayMappings" yaml:"zone_mappings" tf:"varray_mappings"`
	// Unique name identifying this classification of replication group. Required. Updatable
	Name string `json:"name" yaml:"name" tf:"name"`
	// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
	Id string `json:"id" yaml:"id" tf:"id"`
	// Timestamp that shows when this resource was created in ECS
	CreationTime int64 `json:"creation_time" yaml:"creation_time" tf:"creation_time"`
	// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.
	Inactive bool `json:"inactive" yaml:"inactive" tf:"inactive"`
	// Indicated whether the resource is an internal resource
	Internal bool `json:"internal" yaml:"internal" tf:"internal"`
	// Description of the replication group. Default: "". Updatable
	Description string `json:"description" yaml:"description" tf:"description"`
	// Parameter to check if the Vpool can access all Namespace. Default: true. Updatable
	IsAllowAllNamespaces bool `json:"isAllowAllNamespaces" yaml:"isAllowAllNamespaces" tf:"is_allow_all_namespaces"`
	// Parameter to check if the rebalancing is enabled. Default: false. Updatable
	EnableRebalancing bool `json:"enable_rebalancing" yaml:"enable_rebalancing" tf:"enable_rebalancing"`
	// Parameter to check if to use replication targets. Default: false
	UseReplicationTarget bool `json:"useReplicationTarget" yaml:"useReplicationTarget" tf:"use_replication_target"`
	// set full replication flag. Default: false
	IsFullRep bool `json:"isFullRep" yaml:"isFullRep" tf:"is_full_rep"`
}

type VarrayMapping struct {
	// Virtual data center id
	Name string `json:"name" yaml:"name" tf:"name"`
	// Storage pool id
	Value string `json:"value" yaml:"value" tf:"value"`
	// is replication target
	IsReplicationTarget bool `json:"is_replication_target" yaml:"is_replication_target" tf:"is_replication_target"`
}
