//
// Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//

package pkg

// #include "objectscale_client.h"
import "C"

type Attribute struct {
	// Lookup string for this key-value pair
	Key string `json:"key" yaml:"key" tf:"key"`
	// Lookup result for this key-value pair
	Value []string `json:"value" yaml:"value" tf:"value"`
}

// ECS supports access by multiple tenants, where each tenant is defined by a namespace.
type Namespace struct {
	// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier. Required
	Name string `json:"name" yaml:"namespace" tf:"name"`
	// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time
	Id string `json:"id" yaml:"id" tf:"id"`
	// Indicates whether the resource is global
	Global bool `json:"global" yaml:"global" tf:"global"`
	// Indicates whether the resource is remote
	Remote bool `json:"remote" yaml:"remote" tf:"remote"`
	// Hyperlink to the details for this resource
	Link TenancyLink `json:"link" yaml:"link" tf:"link"`
	// Timestamp that shows when this resource was created in ECS
	CreationTime int64 `json:"creation_time" yaml:"creation_time" tf:"creation_time"`
	// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database
	Inactive bool `json:"inactive" yaml:"inactive" tf:"inactive"`
	// Indicated whether the resource is an internal resource
	Internal bool `json:"internal" yaml:"internal" tf:"internal"`
	// Default replication group identifier for this tenant when creating buckets. Required. Updatable
	DefaultDataServicesVpool string `json:"default_data_services_vpool" yaml:"default_data_services_vpool" tf:"default_data_services_vpool"`
	// List of replication group that are allowed access to namespace.
	AllowedVpoolsList []string `json:"allowed_vpools_list" yaml:"allowed_vpools_list" tf:"allowed_vpools_list"`
	// List of replication group that are not allowed access to namespace.
	DisallowedVpoolsList []string `json:"disallowed_vpools_list" yaml:"disallowed_vpools_list" tf:"disallowed_vpools_list"`
	// Comma separated list of namespace admins. Default: "". Updatable
	NamespaceAdmins string `json:"namespace_admins" yaml:"namespace_admins" tf:"namespace_admins"`
	// User Mapping. Default: []. Updatable
	UserMapping []UserMapping `json:"user_mapping" yaml:"user_mapping" tf:"user_mapping"`
	// encryption status of the namesapce. Default: false.
	IsEncryptionEnabled bool `json:"is_encryption_enabled" yaml:"is_encryption_enabled" tf:"is_encryption_enabled"`
	// Default bucket quota size. Default: -1. Updatable.
	DefaultBucketBlockSize int64 `json:"default_bucket_block_size" yaml:"default_bucket_block_size" tf:"default_bucket_block_size"`
	// List of groups from AD Server. Default: "". Updatable
	ExternalGroupAdmins string `json:"external_group_admins" yaml:"external_group_admins" tf:"external_group_admins"`
	// Namespace isStaleAllowed flag. Default: false. Updatable.
	IsStaleAllowed bool `json:"is_stale_allowed" yaml:"is_stale_allowed" tf:"is_stale_allowed"`
	// Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Default: false. Updatable
	IsObjectLockWithAdoAllowed bool `json:"is_object_lock_with_ado_allowed" yaml:"is_object_lock_with_ado_allowed" tf:"is_object_lock_with_ado_allowed"`
	// Namespace isComplianceEnabled flag. Default: false.
	IsComplianceEnabled bool `json:"is_compliance_enabled" yaml:"is_compliance_enabled" tf:"is_compliance_enabled"`
	// Notification Size in GB. Default: -1. Updatable.
	NotificationSize int64 `json:"notificationSize" yaml:"notificationSize" tf:"notification_size"`
	// Block Size in GB. Default: -1. Updatable.
	BlockSize int64 `json:"blockSize" yaml:"blockSize" tf:"block_size"`
	// Notification Size in Count. Default: -1. Updatable.
	NotificationSizeInCount int64 `json:"notificationSizeInCount" yaml:"notificationSizeInCount" tf:"notification_size_in_count"`
	// Block Size in Count. Default: -1. Updatable.
	BlockSizeInCount int64 `json:"blockSizeInCount" yaml:"blockSizeInCount" tf:"block_size_in_count"`
	// Default bucket audit delete expiration. Updatable
	DefaultAuditDeleteExpiration int64 `json:"default_audit_delete_expiration" yaml:"default_audit_delete_expiration" tf:"default_audit_delete_expiration"`
	// retention classes. Default. Updatable
	RetentionClasses RetentionClasses `json:"retention_classes" yaml:"retention_classes" tf:"retention_classes"`
	// root user name
	RootUserName string `json:"root_user_name" yaml:"root_user_name" tf:"root_user_name"`
	// root user password. Default: "".
	RootUserPassword string `json:"root_user_password" yaml:"root_user_password" tf:"root_user_password"`
}

type RetentionClass struct {
	// Name of the retention class. Required. Updatable
	Name string `json:"name" yaml:"name" tf:"name"`
	// Period of the retention class in seconds. Required. Updatable
	Period int64 `json:"period" yaml:"period" tf:"period"`
}

type RetentionClasses struct {
	// Retention class, default: []. Updatable
	RetentionClass []RetentionClass `json:"retention_class" yaml:"retention_class" tf:"retention_class"`
}

type TenancyLink struct {
	//
	Rel string `json:"rel" yaml:"rel" tf:"rel"`
	//
	Href string `json:"href" yaml:"href" tf:"href"`
}

type UserMapping struct {
	// A single-valued attribute indicating the user's IDP domain
	Domain string `json:"domain" yaml:"domain" tf:"domain"`
	// Attributes
	Attributes []Attribute `json:"attributes" yaml:"attributes" tf:"attributes"`
	// Groups
	Groups []string `json:"groups" yaml:"groups" tf:"groups"`
}
