//
// Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//

//! Define the provisioning details.
//!
use crate::client::{ManagementClient, AUTH_HEADER_KEY};
use crate::response::get_content_text;
use anyhow::{bail, Context as _, Result};
use derive_builder::Builder;
use reqwest::header::{ACCEPT, CONTENT_TYPE};
use serde::{Deserialize, Serialize};
use serde_aux::field_attributes::{deserialize_bool_from_anything, deserialize_default_from_null};

#[derive(Clone, Default, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all(serialize = "snake_case", deserialize = "camelCase"))]
pub struct Link {
    pub rel: String,
    pub href: String,
}

#[derive(Clone, Default, Debug, Deserialize, Serialize)]
pub struct MinMaxGovernor {
    pub enforce_retention: bool,
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub minimum_fixed_retention: i64,
    // TODO: need to understand the default value
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub maximum_fixed_retention: i64,
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub minimum_variable_retention: i64,
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub maximum_variable_retention: i64,
}

#[derive(Clone, Default, Debug, Deserialize, Serialize)]
#[serde(rename_all(serialize = "snake_case", deserialize = "camelCase"))]
pub struct MetaData {
    /// The meta key type
    pub datatype: String,
    /// The meta key name
    pub name: String,
    /// The meta key data type
    pub r#type: String,
}

#[derive(Clone, Default, Debug, Deserialize, Serialize)]
#[serde(rename_all(serialize = "snake_case", deserialize = "camelCase"))]
pub struct SearchMetaData {
    /// Getter for the enabled flag.
    pub is_enabled: bool,
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub metadata: Vec<MetaData>,
    /// Getter for maxKeys.
    pub max_keys: i32,
    /// Getter for the mdTokens flag.
    #[serde(alias = "metadata_tokens")]
    pub metadata_tokens: bool,
}

/// Lables for bucket.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "PascalCase")]
pub struct BucketTag {
    /// The key of a tag.
    pub key: String,
    /// The value of a tag.
    pub value: String,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "PascalCase")]
struct TagRequest {
    pub tag_set: Vec<BucketTag>,
    #[serde(rename = "namespace")]
    pub namespace: String,
}

/// Buckets are object containers that are used to control access to objects. ObjectScale supports bucket-to-bucket replication of the objects within a bucket.
#[derive(Builder, Clone, Debug, Default, Deserialize, Serialize)]
#[builder(setter(skip))]
#[serde(rename(serialize = "object_bucket_create"))]
pub struct Bucket {
    /// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier.
    #[builder(setter(into))]
    pub name: String,
    /// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
    pub id: String,
    /// Hyperlink to the details for this resource
    pub link: Link,
    #[builder(setter(into))]
    /// Namespace
    pub namespace: String,
    pub vpool: String,
    /// "Locked" status of a bucket
    pub locked: bool,
    /// Bucket "file system access enabled" status
    pub fs_access_enabled: bool,
    /// Bucket soft quota
    #[serde(alias = "softquota")]
    pub soft_quota: String,
    /// Bucket creation time
    pub created: String,
    /// Bucket isStaleAllowed flag
    pub is_stale_allowed: bool,
    /// If true Object Lock and ADO can be enabled together. See the Admin Guide for more information.
    pub is_object_lock_with_ado_allowed: bool,
    pub is_object_lock_enabled: bool,
    /// Bucket isStaleAllowed flag
    pub is_tso_read_only: bool,
    /// Default object lock retention mode
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub default_object_lock_retention_mode: String,
    /// Default object lock retention years
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub default_object_lock_retention_years: i32,
    /// Default object lock retention days
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub default_object_lock_retention_days: i32,
    /// Default bucket retention
    pub default_retention: i64,
    /// Block size in GB
    pub block_size: i64,
    /// auto-commit interval
    pub auto_commit_period: i64,
    /// Notification size in GB
    pub notification_size: i64,
    /// Block size in count
    #[serde(alias = "blockSizeInCount")]
    pub block_size_in_count: i64,
    /// Notification size in count
    #[serde(alias = "notificationSizeInCount")]
    pub notification_size_in_count: i64,
    /// Bucket isEncryptionEnabled flag
    #[builder(setter(skip = false), default = "false")]
    #[serde(deserialize_with = "deserialize_bool_from_anything")]
    pub is_encryption_enabled: bool,
    /// Default retention value for the bucket.
    pub retention: i64,
    /// Bucket's default group
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub default_group: String,
    /// Flag indicating the Read permission for default group
    pub default_group_file_read_permission: bool,
    /// Flag indicating the file write permission for default group
    pub default_group_file_write_permission: bool,
    /// Flag indicating the file execute permission for default group
    pub default_group_file_execute_permission: bool,
    /// Flag indicating the directory read permission for default group. This is only applicable to folders created within the Filesystem-Enabled bucket. It is not applicable to files/objects
    pub default_group_dir_read_permission: bool,
    /// Flag indicating the directory write permission for default group. This is only applicable to folders created within the Filesystem-Enabled bucket. It is not applicable to files/objects
    pub default_group_dir_write_permission: bool,
    /// Flag indicating the directory execute permission for default group. This is only applicable to folders created within the Filesystem-Enabled bucket. It is not applicable to files/objects
    pub default_group_dir_execute_permission: bool,
    pub min_max_governor: MinMaxGovernor,
    /// Bucket audit delete expiration in seconds
    #[builder(setter(skip = false), default = "-2")]
    pub audit_delete_expiration: i64,
    /// Enable advanced metadata search
    #[serde(alias = "enableAdvancedMetadataSearch")]
    pub enable_advanced_metadata_search: bool,
    #[serde(
        alias = "advancedMetadataSearchTargetName",
        deserialize_with = "deserialize_default_from_null"
    )]
    pub advanced_metadata_search_target_name: String,
    #[serde(
        alias = "advancedMetadataSearchTargetStream",
        deserialize_with = "deserialize_default_from_null"
    )]
    pub advanced_metadata_search_target_stream: String,
    /// Optional. If true the bucket is in the process of being deleted. The bucket will be read only and no changes will be allowed on the bucket until the operation completes.
    pub is_empty_bucket_in_progress: bool,
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub versioning_status: String,
    #[builder(setter(skip = false), default)]
    pub search_metadata: SearchMetaData,
    /// Local object metadata reads bucket flag.
    pub local_object_metadata_reads: bool,
    /// API type
    pub api_type: String,
    /// Bucket owner
    #[builder(setter(skip = false), default)]
    pub owner: String,
    /// Keywords and labels that can be added by a user to a resource to make it easy to find when doing a search.
    #[builder(setter(skip = false), default)]
    #[serde(rename = "TagSet", deserialize_with = "deserialize_default_from_null")]
    pub tags: Vec<BucketTag>,
}

// dose not deserialize all the fields for create bucket response
// as the schema does not align with get bucket response
// would issue get bucket request in addition after creation and send the response accordingly
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CreateBucketResponse {
    pub name: String,
    pub id: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct ListBucketsResponse {
    // Does not align with API description
    #[serde(alias = "object_bucket")]
    pub object_bucket: Vec<Bucket>,
    pub filter: String,
    pub next_marker: Option<String>,
    pub max_buckets: Option<u32>,
    pub next_page_link: Option<String>,
}

impl Bucket {
    pub(crate) fn create(client: &mut ManagementClient, bucket: Bucket) -> Result<String> {
        let request_url = format!("{}object/bucket.json", client.endpoint);
        let body = quick_xml::se::to_string(&bucket)?;
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/xml")
            .body(body)
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to create bucket")?;
        let resp: CreateBucketResponse = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise CreateBucketResponse. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp.name)
    }

    pub(crate) fn get(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
    ) -> Result<Bucket> {
        let request_url = format!(
            "{}object/bucket/{}/info.json?namespace={}",
            client.endpoint, name, namespace,
        );
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get bucket")?;
        let resp: Bucket = serde_json::from_str(&text)
            .with_context(|| format!("Unable to deserialise GetBucket. Body was: \"{}\"", text))?;
        Ok(resp)
    }

    pub(crate) fn add_tag(
        client: &mut ManagementClient,
        bucket_name: &str,
        namespace: &str,
        tags: Vec<BucketTag>,
    ) -> Result<()> {
        let tag_request = TagRequest {
            tag_set: tags,
            namespace: namespace.to_string(),
        };
        let body = serde_json::to_string(&tag_request)?;
        let request_url = format!("{}object/bucket/{}/tags", client.endpoint, bucket_name);
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/json")
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update bucket tags failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn delete_tag(
        client: &mut ManagementClient,
        bucket_name: &str,
        namespace: &str,
        tags: Vec<BucketTag>,
    ) -> Result<()> {
        let tag_request = TagRequest {
            tag_set: tags,
            namespace: namespace.to_string(),
        };
        let body = serde_json::to_string(&tag_request)?;
        let request_url = format!("{}object/bucket/{}/tags", client.endpoint, bucket_name);
        let resp = client
            .http_client
            .delete(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/json")
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Delete bucket tags failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn update_owner(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        owner: &str,
    ) -> Result<()> {
        // // Set Bucket Audit Delete Expiration
        // let request_url = format!(
        //     "{}object/bucket/{}/auditDeleteExpiration?expiration={}&namespace={}",
        //     client.endpoint, bucket.name, bucket.audit_delete_expiration, bucket.namespace,
        // );
        // Update Bucket Owner
        let request_url = format!("{}object/bucket/{}/owner", client.endpoint, name,);
        let body = format!(
            r#"<object_bucket_update_owner><new_owner>{}</new_owner><namespace>{}</namespace><reset_previous_owners>true</reset_previous_owners></object_bucket_update_owner>"#,
            owner, namespace
        );
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/xml")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update bucket owner failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn update(client: &mut ManagementClient, bucket: &Self) -> Result<Self> {
        let current_bucket = Self::get(client, &bucket.name, &bucket.namespace)?;

        if bucket.owner != current_bucket.owner {
            Self::update_owner(client, &bucket.name, &bucket.namespace, &bucket.owner)?;
        }

        if bucket.tags != current_bucket.tags {
            if !current_bucket.tags.is_empty() {
                Self::delete_tag(client, &bucket.name, &bucket.namespace, current_bucket.tags)?;
            }
            if !bucket.tags.is_empty() {
                Self::add_tag(client, &bucket.name, &bucket.namespace, bucket.tags.clone())?;
            }
        }

        Self::get(client, &bucket.name, &bucket.namespace)
    }

    pub(crate) fn delete(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        empty_bucket: bool,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/deactivate.json?namespace={}&emptyBucket={}",
            client.endpoint, name, namespace, empty_bucket,
        );
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        if !resp.status().is_success() {
            bail!("Delete bucket failed: {}", resp.text()?);
        } else if resp.status().as_u16() == 202 {
            // TODO: whether to check response
            // it may last for a while
            bail!("Deletion ongoing");
        } else {
            Ok(())
        }
    }

    pub(crate) fn list(
        client: &mut ManagementClient,
        namespace: &str,
        name_prefix: &str,
    ) -> Result<Vec<Bucket>> {
        let prefix = if name_prefix.is_empty() {
            "".to_string()
        } else {
            format!("&name={}", name_prefix)
        };
        let request_url = format!(
            "{}object/bucket.json?namespace={}{}",
            client.endpoint, namespace, prefix,
        );
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to list bucket")?;
        let mut resp: ListBucketsResponse = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise ListBuckestResponse. Body was: \"{}\"",
                text
            )
        })?;
        let mut buckets: Vec<Bucket> = vec![];
        buckets.extend(resp.object_bucket);
        while let Some(marker) = resp.next_marker {
            let request_url = format!(
                "{}object/bucket.json?namespace={}{}&marker={}",
                client.endpoint, namespace, prefix, marker,
            );
            let response = client
                .http_client
                .get(request_url)
                .header(ACCEPT, "application/json")
                .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
                .send()?;
            let text = get_content_text(response).with_context(|| "Failed to list bucket")?;
            resp = serde_json::from_str(&text).with_context(|| {
                format!(
                    "Unable to deserialise ListBucketsResponse. Body was: \"{}\"",
                    text
                )
            })?;
            buckets.extend(resp.object_bucket);
        }
        Ok(buckets)
    }
}

/// A VDC identifies the nodes that are participating in an ObjectScale instance.
#[derive(Builder, Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Vdc {
    /// Indicates whether the resource is global.
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub global: bool,
    /// Indicates whether the resource is remote.
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub remote: bool,
    // TODO:
    // #[serde(deserialize_with = "deserialize_default_from_null")]
    // pub vdc: String,
    /// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier.
    pub name: String,
    /// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
    pub id: String,
    /// Hyperlink to the details for this resource
    pub link: Link,
    /// Timestamp that shows when this resource was created in ECS
    #[serde(
        deserialize_with = "deserialize_default_from_null",
        rename = "creation_time"
    )]
    pub creation_time: String,
    /// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.
    pub inactive: bool,
    /// Indicated whether the resource is an internal resource
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub internal: bool,
    /// VDC id
    pub vdc_id: String,
    /// VDC name
    pub vdc_name: String,
    /// VDC end points
    #[serde(rename = "interVdcEndPoints")]
    pub inter_vdc_endpoints: String,
    /// VDC cmd end points
    #[serde(rename = "interVdcCmdEndPoints")]
    pub inter_vdc_cmd_endpoints: String,
    /// The management end points for the VDC
    #[serde(rename = "managementEndPoints")]
    pub management_endpoints: String,
    /// Secret key for this VDC
    pub secret_keys: String,
    /// True of vdc is permanently failed, false otherwise.
    pub permanently_failed: bool,
    /// True of this vdc is local, false otherwise
    pub local: bool,
    /// True of this vdc is hosted, false otherwise
    pub hosted: bool,
    /// True of this vdc is enabled for encryption, false otherwise
    #[serde(rename = "is_encryption_enabled")]
    pub is_encryption_enabled: bool,
}

#[derive(Deserialize)]
struct VdcList {
    vdc: Vec<Vdc>,
}

impl Vdc {
    pub(crate) fn get(client: &mut ManagementClient, name: &str) -> Result<Self> {
        let request_url = format!("{}object/vdcs/vdc/{}", client.endpoint, name);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get vdc")?;
        let resp: Self = serde_json::from_str(&text)
            .with_context(|| format!("Unable to deserialise Vdc. Body was: \"{}\"", text))?;
        Ok(resp)
    }

    pub(crate) fn list(client: &mut ManagementClient) -> Result<Vec<Self>> {
        let request_url = format!("{}object/vdcs/vdc/list", client.endpoint);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to list VDCs")?;
        let resp: VdcList = serde_json::from_str(&text)
            .with_context(|| format!("Unable to deserialise VdcList. Body was: \"{}\"", text))?;
        Ok(resp.vdc)
    }
}

/// Vdc Keystore is to manage the certificates of a virtual data center (VDC)
#[derive(Builder, Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
pub struct VdcKeystore {
    /// Keystore certificate chain in PEM format
    pub chain: String,
    /// The private key used to sign the certificate in PEM format.
    #[serde(default)]
    pub private_key: String,
}

impl VdcKeystore {
    pub(crate) fn get(client: &mut ManagementClient) -> Result<Self> {
        let request_url = format!("{}vdc/keystore", client.endpoint);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get vdc keystore")?;
        let resp: Self = serde_json::from_str(&text).with_context(|| {
            format!("Unable to deserialise VdcKeystore. Body was: \"{}\"", text)
        })?;
        Ok(resp)
    }

    pub(crate) fn update(client: &mut ManagementClient, keystore: &Self) -> Result<()> {
        let request_url = format!("{}vdc/keystore", client.endpoint);
        let body = format!(
            r#"{{"key_and_certificate":{{"private_key":"{}","certificate_chain":"{}"}}}}"#,
            keystore.private_key, keystore.chain
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/json")
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update vdc keystore failed: {}", resp.text()?);
        }
        Ok(())
    }
}

/// Storage pool is a logical construct that contains physical nodes.
#[derive(Builder, Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StoragePool {
    /// Storage pool name
    pub name: String,
    /// Storage pool id
    pub id: String,
    /// Description
    pub description: String,
    /// Flag indicating that storage pool is protected
    pub is_protected: bool,
    /// Flag indicating that cold storage encoding is enabled
    pub is_cold_storage_enabled: bool,
    /// Number of Data Blocks in EC Scheme
    pub number_of_data_blocks: u64,
    /// Number of Code Blocks in EC Scheme
    pub number_of_code_blocks: u64,
    /// Threshold percent at which warning alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert
    pub warning_alert_at: i64,
    /// Threshold percent at which error alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert
    pub error_alert_at: i64,
    /// Threshold percent at which critical alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert
    pub critical_alert_at: i64,
    /// Drive technology of VArray
    pub label: String,
    /// Drive technology of VArray
    pub drive_technology: String,
    /// flag for status, -1 for null, 0 ~ 6 for value
    pub status: i64,
}

#[derive(Deserialize)]
struct StoragePoolList {
    varray: Vec<StoragePool>,
}

impl StoragePool {
    pub(crate) fn get(client: &mut ManagementClient, id: &str) -> Result<Self> {
        let request_url = format!("{}vdc/data-services/varrays/{}", client.endpoint, id);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get storage pool")?;
        let resp: Self = serde_json::from_str(&text).with_context(|| {
            format!("Unable to deserialise StoragePool. Body was: \"{}\"", text)
        })?;
        Ok(resp)
    }

    pub(crate) fn list(client: &mut ManagementClient) -> Result<Vec<Self>> {
        let request_url = format!("{}vdc/data-services/varrays", client.endpoint);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to list storage pools")?;
        let resp: StoragePoolList = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise StoragePoolList. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp.varray)
    }
}
