//
// Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//

//! Define the provisioning details.
//!
use crate::client::{ManagementClient, AUTH_HEADER_KEY};
use crate::response::get_content_text;
use anyhow::{bail, Context as _, Result};
use derive_builder::Builder;
use reqwest::header::{ACCEPT, CONTENT_TYPE};
use serde::{Deserialize, Serialize};
use serde_aux::field_attributes::{deserialize_bool_from_anything, deserialize_default_from_null};

#[derive(Clone, Default, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct ProvisioningLink {
    pub rel: String,
    pub href: String,
}

#[derive(Clone, Default, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct MinMaxGovernor {
    /// enforce retention: Default: false. Updatable
    pub enforce_retention: bool,
    /// minimum fixed retention: Default: 0. Updatable
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub minimum_fixed_retention: i64,
    /// maximum fixed retention: Default: 0. Updatable
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub maximum_fixed_retention: i64,
    /// minimum variable retention: Default: 0. Updatable
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub minimum_variable_retention: i64,
    /// maximum variable retention: Default: 0. Updatable
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub maximum_variable_retention: i64,
}

#[derive(Clone, Default, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all(serialize = "snake_case", deserialize = "camelCase"))]
pub struct MetaData {
    /// The meta key type. Required
    pub datatype: String,
    /// The meta key name. Required
    pub name: String,
    /// The meta key data type. Required
    pub r#type: String,
}

#[derive(Clone, Default, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all(serialize = "snake_case", deserialize = "camelCase"))]
pub struct SearchMetaData {
    /// Getter for the enabled flag. It cannot be re-enabled once disabled. Updatable.
    pub is_enabled: bool,
    /// Metadata list. Default: []
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub metadata: Vec<MetaData>,
    /// Getter for maxKeys.
    pub max_keys: i32,
    /// Getter for the mdTokens flag.
    #[serde(rename = "metadata_tokens")]
    pub metadata_tokens: bool,
}

/// Lables for bucket.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "PascalCase")]
pub struct BucketTag {
    /// The key of a tag.
    pub key: String,
    /// The value of a tag.
    pub value: String,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "PascalCase")]
struct TagRequest {
    pub tag_set: Vec<BucketTag>,
    #[serde(rename = "namespace")]
    pub namespace: String,
}

/// Buckets are object containers that are used to control access to objects. ObjectScale supports bucket-to-bucket replication of the objects within a bucket.
#[derive(Builder, Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
#[builder(setter(skip))]
#[serde(rename(serialize = "object_bucket_create"))]
pub struct Bucket {
    /// Bucket name. Required.
    #[builder(setter(into))]
    pub name: String,
    /// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
    pub id: String,
    /// Hyperlink to the details for this resource
    pub link: ProvisioningLink,
    /// Namespace. Required.
    #[builder(setter(into))]
    pub namespace: String,
    pub vpool: String,
    /// "Locked" status of a bucket
    pub locked: bool,
    /// flag indicating whether file-system is enabled for this bucket. is_object_lock_enabled and fs_access_enabled cannot be true at the same time. Default: false.
    #[serde(rename(serialize = "filesystem_enabled"))]
    #[builder(setter(skip = false), default)]
    pub fs_access_enabled: bool,
    /// Bucket soft quota
    #[serde(rename = "softquota")]
    pub soft_quota: String,
    /// Bucket creation time
    pub created: String,
    /// Bucket isStaleAllowed flag. Default: false. Updatable
    #[builder(setter(skip = false), default)]
    pub is_stale_allowed: bool,
    /// If true Object Lock and ADO can be enabled together. It cannot be changed once enabled. Default: false. Updatable
    #[builder(setter(skip = false), default)]
    pub is_object_lock_with_ado_allowed: bool,
    /// Indicates the Retention mode for the specified object. is_object_lock_enabled and fs_access_enabled cannot be true at the same time. Can only set from false to true. Default: false. Updatable
    #[builder(setter(skip = false), default)]
    pub is_object_lock_enabled: bool,
    /// Bucket is_tso_read_only flag. Can only be true if is_stale_allowed is true. Default: false.
    #[builder(setter(skip = false), default)]
    pub is_tso_read_only: bool,
    /// Default object lock retention mode. Can be: GOVERNANCE or COMPLIANCE. Default: "". Updatable only when is_object_lock_enabled is true
    #[serde(deserialize_with = "deserialize_default_from_null")]
    #[builder(setter(skip = false, into), default)]
    pub default_object_lock_retention_mode: String,
    /// Default object lock retention years. Either Days or Years must be specified, but not both. Default: 0. Updatable only when is_object_lock_enabled is true
    #[serde(deserialize_with = "deserialize_default_from_null")]
    #[builder(setter(skip = false), default)]
    pub default_object_lock_retention_years: i64,
    /// Default object lock retention days. Either Days or Years must be specified, but not both. Default: 0. Updatable only when is_object_lock_enabled is true
    #[serde(deserialize_with = "deserialize_default_from_null")]
    #[builder(setter(skip = false), default)]
    pub default_object_lock_retention_days: i64,
    /// Default bucket retention
    pub default_retention: i64,
    /// Default autocommit period in seconds. If fs_access_enabled is false, this value can't be updated. Default: 0. Updatable
    #[serde(rename(serialize = "autocommit_period"))]
    #[builder(setter(skip = false), default)]
    pub auto_commit_period: i64,
    /// Block size in GB. Cannot be less than 1GB or use decimal values. Can be set to -1 to indicate quota value not defined. Default: -1. Updatable
    #[builder(setter(skip = false), default = -1)]
    #[serde(rename(serialize = "blockSize"))]
    pub block_size: i64,
    /// Notification size in GB. Cannot be less than 1GB or use decimal values. Can be set to -1 to indicate quota value not defined. Default: -1. Updatable
    #[builder(setter(skip = false), default = -1)]
    #[serde(rename(serialize = "notificationSize"))]
    pub notification_size: i64,
    /// Block size in count. Default: -1.
    #[serde(rename = "blockSizeInCount")]
    #[builder(setter(skip = false), default = -1)]
    pub block_size_in_count: i64,
    /// Notification size in count. Default: -1.
    #[serde(rename = "notificationSizeInCount")]
    #[builder(setter(skip = false), default = -1)]
    pub notification_size_in_count: i64,
    /// Bucket isEncryptionEnabled flag
    #[builder(setter(skip = false), default)]
    #[serde(deserialize_with = "deserialize_bool_from_anything")]
    pub is_encryption_enabled: bool,
    /// Default retention period in seconds. Should be less than maximum_fixed_retention. Default: 0. Updatable
    #[builder(setter(skip = false), default)]
    pub retention: i64,
    /// Bucket's default group. Default: "". Updatable
    #[serde(deserialize_with = "deserialize_default_from_null")]
    #[builder(setter(skip = false, into), default)]
    pub default_group: String,
    /// Flag indicating the Read permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[builder(setter(skip = false), default)]
    pub default_group_file_read_permission: bool,
    /// Flag indicating the file write permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[builder(setter(skip = false), default)]
    pub default_group_file_write_permission: bool,
    /// Flag indicating the file execute permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[builder(setter(skip = false), default)]
    pub default_group_file_execute_permission: bool,
    /// Flag indicating the directory read permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[builder(setter(skip = false), default)]
    pub default_group_dir_read_permission: bool,
    /// Flag indicating the directory write permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[builder(setter(skip = false), default)]
    pub default_group_dir_write_permission: bool,
    /// Flag indicating the directory execute permission for default group. This is only applicable when fs_access_enabled is true. Default: false. Updatable
    #[builder(setter(skip = false), default)]
    pub default_group_dir_execute_permission: bool,
    /// default retention period setting. Default: see MinMaxGovernor. Updatable
    #[builder(setter(skip = false), default)]
    pub min_max_governor: MinMaxGovernor,
    /// Bucket audit delete expiration in seconds. Default: -2. Updatable
    #[builder(setter(skip = false), default = "-2")]
    pub audit_delete_expiration: i64,
    /// Enable advanced metadata search
    #[serde(rename = "enableAdvancedMetadataSearch")]
    pub enable_advanced_metadata_search: bool,
    #[serde(
        rename = "advancedMetadataSearchTargetName",
        deserialize_with = "deserialize_default_from_null"
    )]
    pub advanced_metadata_search_target_name: String,
    #[serde(
        rename = "advancedMetadataSearchTargetStream",
        deserialize_with = "deserialize_default_from_null"
    )]
    pub advanced_metadata_search_target_stream: String,
    /// If true the bucket is in the process of being deleted. The bucket will be read only and no changes will be allowed on the bucket until the operation completes.
    pub is_empty_bucket_in_progress: bool,
    /// versioning status for the bucket. Can be "" | Enabled | Suspended. It can be only "Enabled" when fs_access_enabled is false. During creation, it can be "" or "Enabled".Then it can switch between "Enabled" and "Suspended". Default: "". Updatable
    #[serde(deserialize_with = "deserialize_default_from_null")]
    #[builder(setter(skip = false, into), default)]
    pub versioning_status: String,
    /// Searchable tags assigned to objects created within the bucket. Default: see SearchMetaData. Updatable
    #[builder(setter(skip = false), default)]
    pub search_metadata: SearchMetaData,
    /// Local object metadata reads bucket flag. Default: false. Updatable
    // TODO: how to enable this value during creation
    #[builder(setter(skip = false), default)]
    pub local_object_metadata_reads: bool,
    /// API type
    pub api_type: String,
    /// Bucket owner. If empty, it would be current user. Default: "". Updatable
    #[builder(setter(skip = false), default)]
    pub owner: String,
    /// Keywords and labels that can be added by a user to a resource to make it easy to find when doing a search. Default: []. Updatable
    #[builder(setter(skip = false), default)]
    #[serde(rename = "TagSet", deserialize_with = "deserialize_default_from_null")]
    pub tags: Vec<BucketTag>,
}

fn is_zero(s: &i64) -> bool {
    *s == 0
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "PascalCase", rename(serialize = "DefaultRetention"))]
struct DefaultRetention {
    pub mode: String,
    #[serde(skip_serializing_if = "is_zero")]
    pub years: i64,
    #[serde(skip_serializing_if = "is_zero")]
    pub days: i64,
}

#[derive(Debug, PartialEq, Eq, Serialize)]
struct DefaultGroup {
    pub default_group: String,
    pub default_group_file_read_permission: String,
    pub default_group_file_write_permission: String,
    pub default_group_file_execute_permission: String,
    pub default_group_dir_read_permission: String,
    pub default_group_dir_write_permission: String,
    pub default_group_dir_execute_permission: String,
    pub namespace: String,
}

impl DefaultGroup {
    fn from(bucket: &Bucket) -> Self {
        Self {
            default_group: bucket.default_group.to_string(),
            default_group_file_read_permission: bucket
                .default_group_file_read_permission
                .to_string(),
            default_group_file_write_permission: bucket
                .default_group_file_write_permission
                .to_string(),
            default_group_file_execute_permission: bucket
                .default_group_file_execute_permission
                .to_string(),
            default_group_dir_read_permission: bucket.default_group_dir_read_permission.to_string(),
            default_group_dir_write_permission: bucket
                .default_group_dir_write_permission
                .to_string(),
            default_group_dir_execute_permission: bucket
                .default_group_dir_execute_permission
                .to_string(),
            namespace: bucket.namespace.to_string(),
        }
    }
}

#[derive(Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
struct Quota {
    pub block_size: i64,
    pub notification_size: i64,
    pub namespace: String,
}

impl Quota {
    fn from(bucket: &Bucket) -> Self {
        Self {
            block_size: bucket.block_size,
            notification_size: bucket.notification_size,
            namespace: bucket.namespace.to_string(),
        }
    }

    fn is_not_set(&self) -> bool {
        self.block_size == -1 && self.notification_size == -1
    }
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct ListBucketsResponse {
    // Does not align with API description
    #[serde(rename = "object_bucket")]
    pub object_bucket: Vec<Bucket>,
    pub filter: String,
    pub next_marker: Option<String>,
    pub max_buckets: Option<u32>,
    pub next_page_link: Option<String>,
}

impl Bucket {
    // dose not deserialize all the fields for create bucket response
    // as the schema does not align with get bucket response
    // would issue get bucket request in addition after creation and send the response accordingly
    pub(crate) fn create(client: &mut ManagementClient, bucket: &Bucket) -> Result<()> {
        let request_url = format!("{}object/bucket.json", client.endpoint);
        let body = quick_xml::se::to_string(bucket)?;
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/xml")
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to create bucket")?;
        Ok(())
    }

    pub(crate) fn get(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
    ) -> Result<Bucket> {
        let request_url = format!(
            "{}object/bucket/{}/info.json?namespace={}",
            client.endpoint, name, namespace,
        );
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get bucket")?;
        let resp: Bucket = serde_json::from_str(&text)
            .with_context(|| format!("Unable to deserialise GetBucket. Body was: \"{}\"", text))?;
        Ok(resp)
    }

    // pub(crate) fn get_copy_policy(
    //     client: &mut ManagementClient,
    //     name: &str,
    //     namespace: &str,
    // ) -> Result<()> {
    //     let request_url = format!(
    //         "{}object/bucket/{}/copypolicy?account={}",
    //         client.endpoint, name, namespace,
    //     );
    //     let resp = client
    //         .http_client
    //         .get(request_url)
    //         .header(ACCEPT, "application/json")
    //         .header(CONTENT_TYPE, "application/json")
    //         .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
    //         .send()?;
    //     let text = get_content_text(resp).with_context(|| "Failed to get bucket copy policy")?;
    //     // let resp: Bucket = serde_json::from_str(&text)
    //     //     .with_context(|| format!("Unable to deserialise GetBucket. Body was: \"{}\"", text))?;
    //     // Ok(resp)
    //     println!("Get bucket copy policy: {}", text);
    //     Ok(())
    // }

    pub(crate) fn set_quota(
        client: &mut ManagementClient,
        name: &str,
        bucket: &Bucket,
    ) -> Result<()> {
        let request_url = format!("{}object/bucket/{}/quota", client.endpoint, name);
        let quota = Quota::from(bucket);
        let body = serde_json::to_string(&quota)?;
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set quota")?;
        Ok(())
    }

    pub(crate) fn delete_quota(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/quota?namespace={}",
            client.endpoint, name, namespace
        );
        let resp = client
            .http_client
            .delete(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set quota")?;
        Ok(())
    }

    pub(crate) fn add_tag(
        client: &mut ManagementClient,
        bucket_name: &str,
        namespace: &str,
        tags: Vec<BucketTag>,
    ) -> Result<()> {
        let tag_request = TagRequest {
            tag_set: tags,
            namespace: namespace.to_string(),
        };
        let body = serde_json::to_string(&tag_request)?;
        let request_url = format!("{}object/bucket/{}/tags", client.endpoint, bucket_name);
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/json")
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update bucket tags failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn delete_tag(
        client: &mut ManagementClient,
        bucket_name: &str,
        namespace: &str,
        tags: Vec<BucketTag>,
    ) -> Result<()> {
        let tag_request = TagRequest {
            tag_set: tags,
            namespace: namespace.to_string(),
        };
        let body = serde_json::to_string(&tag_request)?;
        let request_url = format!("{}object/bucket/{}/tags", client.endpoint, bucket_name);
        let resp = client
            .http_client
            .delete(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/json")
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Delete bucket tags failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn set_auto_commit_period(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        period: i64,
    ) -> Result<()> {
        let request_url = format!("{}object/bucket/{}/autocommit", client.endpoint, name,);
        let body = format!(
            r#"{{"autocommit": "{}","namespace": "{}"}}"#,
            period, namespace
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set auto commit period")?;
        Ok(())
    }

    pub(crate) fn set_bucket_retention(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        retention: i64,
        min_max_governor: &MinMaxGovernor,
    ) -> Result<()> {
        let request_url = format!("{}object/bucket/{}/retention", client.endpoint, name,);
        let body = format!(
            r#"{{"period": "{}","namespace": "{}", "min_max_governor": {}}}"#,
            retention,
            namespace,
            serde_json::to_string(min_max_governor)?,
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set bucket retention")?;
        Ok(())
    }

    pub(crate) fn enable_object_lock(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/object-lock-enable?namespace={}",
            client.endpoint, name, namespace
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        get_content_text(resp).with_context(|| "Failed to enable object lock")?;
        Ok(())
    }

    pub(crate) fn set_default_lock_configuration(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        mode: &str,
        years: i64,
        days: i64,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/object-lock-config?namespace={}",
            client.endpoint, name, namespace
        );
        let body = format!(
            r#"<ObjectLockConfiguration><ObjectLockEnabled>Enabled</ObjectLockEnabled><Rule>{}</Rule></ObjectLockConfiguration>"#,
            quick_xml::se::to_string(&DefaultRetention {
                mode: mode.to_string(),
                years,
                days
            })?,
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/xml")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set default lock configuration")?;
        Ok(())
    }

    pub(crate) fn update_owner(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        owner: &str,
    ) -> Result<()> {
        let request_url = format!("{}object/bucket/{}/owner", client.endpoint, name,);
        let body = format!(
            r#"<object_bucket_update_owner><new_owner>{}</new_owner><namespace>{}</namespace><reset_previous_owners>true</reset_previous_owners></object_bucket_update_owner>"#,
            owner, namespace
        );
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/xml")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update bucket owner failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn set_default_group(
        client: &mut ManagementClient,
        name: &str,
        bucket: &Bucket,
    ) -> Result<()> {
        let request_url = format!("{}object/bucket/{}/defaultGroup", client.endpoint, name);
        let default_group = DefaultGroup::from(bucket);
        let body = serde_json::to_string(&default_group)?;
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set default group")?;
        Ok(())
    }

    pub(crate) fn set_versioning(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        versioning: &str,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/versioning?namespace={}",
            client.endpoint, name, namespace
        );
        let body = format!(r#"{{"Status":"{}"}}"#, versioning);
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set versioning")?;
        Ok(())
    }

    pub(crate) fn set_audit_delete_expiration(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        expiration: i64,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/auditDeleteExpiration?namespace={}&expiration={}",
            client.endpoint, name, namespace, expiration
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set audit delete expiration")?;
        Ok(())
    }

    pub(crate) fn set_is_stale_allowed(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        is_stale_allowed: bool,
    ) -> Result<()> {
        let request_url = format!("{}object/bucket/{}/isstaleallowed", client.endpoint, name,);
        let body = format!(
            r#"{{"is_stale_allowed":"{}","namespace":"{}"}}"#,
            is_stale_allowed, namespace
        );
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set audit delete expiration")?;
        Ok(())
    }

    pub(crate) fn enable_object_lock_with_ado_allowd(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/allow-object-lock-with-ado?namespace={}",
            client.endpoint, name, namespace
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        get_content_text(resp).with_context(|| "Failed to enable object lock with ado allowd")?;
        Ok(())
    }

    pub(crate) fn set_local_object_metadata_reads(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        enabled: bool,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/set-local-object-metadata-reads?namespace={}&enabled={}",
            client.endpoint, name, namespace, enabled,
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        get_content_text(resp).with_context(|| "Failed to set local object metadata reads")?;
        Ok(())
    }

    pub(crate) fn deactivate_meta_search(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/searchmetadata?namespace={}",
            client.endpoint, name, namespace,
        );
        let resp = client
            .http_client
            .delete(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        get_content_text(resp).with_context(|| "Failed to deactivate meta search")?;
        Ok(())
    }

    pub(crate) fn update(client: &mut ManagementClient, bucket: &Self) -> Result<bool> {
        let current_bucket = Self::get(client, &bucket.name, &bucket.namespace)?;
        let mut updated = false;

        if !bucket.owner.is_empty() && bucket.owner != current_bucket.owner {
            updated = true;
            Self::update_owner(client, &bucket.name, &bucket.namespace, &bucket.owner)?;
        }

        if bucket.tags != current_bucket.tags {
            updated = true;
            if !current_bucket.tags.is_empty() {
                Self::delete_tag(
                    client,
                    &bucket.name,
                    &bucket.namespace,
                    current_bucket.tags.clone(),
                )?;
            }
            if !bucket.tags.is_empty() {
                Self::add_tag(client, &bucket.name, &bucket.namespace, bucket.tags.clone())?;
            }
        }

        if bucket.auto_commit_period != current_bucket.auto_commit_period {
            updated = true;
            Self::set_auto_commit_period(
                client,
                &bucket.name,
                &bucket.namespace,
                bucket.auto_commit_period,
            )?;
        }

        if bucket.min_max_governor != current_bucket.min_max_governor
            || bucket.retention != current_bucket.retention
        {
            updated = true;
            Self::set_bucket_retention(
                client,
                &bucket.name,
                &bucket.namespace,
                bucket.retention,
                &bucket.min_max_governor,
            )?;
        }

        if current_bucket.fs_access_enabled {
            let default_group = DefaultGroup::from(bucket);
            let current_default_group = DefaultGroup::from(&current_bucket);
            if default_group != current_default_group {
                updated = true;
                Self::set_default_group(client, &bucket.name, bucket)?;
            }
        }

        if !current_bucket.fs_access_enabled {
            if bucket.versioning_status != current_bucket.versioning_status {
                updated = true;
                Self::set_versioning(
                    client,
                    &bucket.name,
                    &bucket.namespace,
                    &bucket.versioning_status,
                )?;
            }

            if bucket.is_object_lock_enabled && !current_bucket.is_object_lock_enabled {
                updated = true;
                Self::enable_object_lock(client, &bucket.name, &bucket.namespace)?;
            }

            if bucket.is_object_lock_enabled
                && (bucket.default_object_lock_retention_mode
                    != current_bucket.default_object_lock_retention_mode
                    || bucket.default_object_lock_retention_years
                        != current_bucket.default_object_lock_retention_years
                    || bucket.default_object_lock_retention_days
                        != current_bucket.default_object_lock_retention_days)
            {
                updated = true;
                Self::set_default_lock_configuration(
                    client,
                    &bucket.name,
                    &bucket.namespace,
                    &bucket.default_object_lock_retention_mode,
                    bucket.default_object_lock_retention_years,
                    bucket.default_object_lock_retention_days,
                )?;
            }
        }

        let quota = Quota::from(bucket);
        let current_quota = Quota::from(&current_bucket);
        if quota != current_quota {
            updated = true;
            if quota.is_not_set() {
                Self::delete_quota(client, &bucket.name, &bucket.namespace)?;
            } else {
                Self::set_quota(client, &bucket.name, bucket)?;
            }
        }

        if bucket.audit_delete_expiration != current_bucket.audit_delete_expiration {
            updated = true;
            Self::set_audit_delete_expiration(
                client,
                &bucket.name,
                &bucket.namespace,
                bucket.audit_delete_expiration,
            )?;
        }

        if bucket.is_stale_allowed != current_bucket.is_stale_allowed {
            updated = true;
            Self::set_is_stale_allowed(
                client,
                &bucket.name,
                &bucket.namespace,
                bucket.is_stale_allowed,
            )?;
        }

        if bucket.is_object_lock_with_ado_allowed && !current_bucket.is_object_lock_with_ado_allowed {
            updated = true;
            Self::enable_object_lock_with_ado_allowd(client, &bucket.name, &bucket.namespace)?;
        }

        if bucket.local_object_metadata_reads != current_bucket.local_object_metadata_reads {
            updated = true;
            Self::set_local_object_metadata_reads(
                client,
                &bucket.name,
                &bucket.namespace,
                bucket.local_object_metadata_reads,
            )?;
        }
        if !bucket.search_metadata.is_enabled && current_bucket.search_metadata.is_enabled {
            updated = true;
            Self::deactivate_meta_search(client, &bucket.name, &bucket.namespace)?;
        }      

        Ok(updated)
    }

    pub(crate) fn delete(
        client: &mut ManagementClient,
        name: &str,
        namespace: &str,
        empty_bucket: bool,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/bucket/{}/deactivate.json?namespace={}&emptyBucket={}",
            client.endpoint, name, namespace, empty_bucket,
        );
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        if !resp.status().is_success() {
            bail!("Delete bucket failed: {}", resp.text()?);
        } else if resp.status().as_u16() == 202 {
            // TODO: whether to check response
            // it may last for a while
            bail!("Deletion ongoing");
        } else {
            Ok(())
        }
    }

    pub(crate) fn list(
        client: &mut ManagementClient,
        namespace: &str,
        name_prefix: &str,
    ) -> Result<Vec<Bucket>> {
        let prefix = if name_prefix.is_empty() {
            "".to_string()
        } else {
            format!("&name={}", name_prefix)
        };
        let request_url = format!(
            "{}object/bucket.json?namespace={}{}",
            client.endpoint, namespace, prefix,
        );
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to list bucket")?;
        let mut resp: ListBucketsResponse = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise ListBuckestResponse. Body was: \"{}\"",
                text
            )
        })?;
        let mut buckets: Vec<Bucket> = vec![];
        buckets.extend(resp.object_bucket);
        while let Some(marker) = resp.next_marker {
            let request_url = format!(
                "{}object/bucket.json?namespace={}{}&marker={}",
                client.endpoint, namespace, prefix, marker,
            );
            let response = client
                .http_client
                .get(request_url)
                .header(ACCEPT, "application/json")
                .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
                .send()?;
            let text = get_content_text(response).with_context(|| "Failed to list bucket")?;
            resp = serde_json::from_str(&text).with_context(|| {
                format!(
                    "Unable to deserialise ListBucketsResponse. Body was: \"{}\"",
                    text
                )
            })?;
            buckets.extend(resp.object_bucket);
        }
        Ok(buckets)
    }
}

/// A VDC identifies the nodes that are participating in an ObjectScale instance.
#[derive(Builder, Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
#[builder(setter(skip))]
pub struct Vdc {
    /// Indicates whether the resource is global.
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub global: bool,
    /// Indicates whether the resource is remote.
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub remote: bool,
    // TODO:
    // #[serde(deserialize_with = "deserialize_default_from_null")]
    // pub vdc: String,
    /// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier.
    pub name: String,
    /// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
    pub id: String,
    /// Hyperlink to the details for this resource
    pub link: ProvisioningLink,
    /// Timestamp that shows when this resource was created in ECS
    #[serde(
        deserialize_with = "deserialize_default_from_null",
        rename = "creation_time"
    )]
    pub creation_time: String,
    /// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.
    pub inactive: bool,
    /// Indicated whether the resource is an internal resource
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub internal: bool,
    /// VDC id
    pub vdc_id: String,
    /// VDC name. Required. Updatable
    #[builder(setter(into, skip = false))]
    pub vdc_name: String,
    /// VDC end points. Required. Updatable
    #[builder(setter(into, skip = false))]
    #[serde(rename = "interVdcEndPoints")]
    pub inter_vdc_endpoints: String,
    /// VDC cmd end points. Required. Updatable
    #[builder(setter(into, skip = false))]
    #[serde(rename = "interVdcCmdEndPoints")]
    pub inter_vdc_cmd_endpoints: String,
    /// The management end points for the VDC. Required. Updatable
    #[builder(setter(into, skip = false))]
    #[serde(rename = "managementEndPoints")]
    pub management_endpoints: String,
    /// Secret key for this VDC. Required. Updatable
    #[builder(setter(into, skip = false))]
    pub secret_keys: String,
    /// True of vdc is permanently failed, false otherwise.
    pub permanently_failed: bool,
    /// True of this vdc is local, false otherwise
    pub local: bool,
    /// True of this vdc is hosted, false otherwise
    pub hosted: bool,
    /// True of this vdc is enabled for encryption, false otherwise
    #[serde(rename = "is_encryption_enabled")]
    pub is_encryption_enabled: bool,
}

#[derive(Deserialize)]
struct VdcList {
    vdc: Vec<Vdc>,
}

impl Vdc {
    pub(crate) fn create(client: &mut ManagementClient, vdc: &Self) -> Result<()> {
        let request_url = format!("{}object/vdcs/vdc/{}", client.endpoint, vdc.vdc_name);
        let body = format!(
            r#"{{"vdcName":"{}","interVdcEndPoints":"{}","interVdcCmdEndPoints":"{}", "managementEndPoints":"{}", "secretKeys":"{}"}}"#,
            vdc.vdc_name,
            vdc.inter_vdc_endpoints,
            vdc.inter_vdc_cmd_endpoints,
            vdc.management_endpoints,
            vdc.secret_keys
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Create vdc failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn get(client: &mut ManagementClient, name: &str) -> Result<Self> {
        let request_url = format!("{}object/vdcs/vdc/{}", client.endpoint, name);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get vdc")?;
        let resp: Self = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise Vdc from get response. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp)
    }

    pub(crate) fn get_by_id(client: &mut ManagementClient, id: &str) -> Result<Self> {
        let request_url = format!("{}object/vdcs/vdcid/{}", client.endpoint, id);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get vdc")?;
        let resp: Self = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise Vdc from get by id response. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp)
    }

    pub(crate) fn update_vdc(client: &mut ManagementClient, vdc: &Self) -> Result<()> {
        let request_url = format!("{}object/vdcs/multivdc", client.endpoint);
        let body = format!(
            r#"{{"vdcs": [{{"vdcId":"{}","vdcName":"{}","interVdcEndPoints":"{}","interVdcCmdEndPoints":"{}", "managementEndPoints":"{}", "secretKeys":"{}"}}]}}"#,
            vdc.id,
            vdc.name,
            vdc.inter_vdc_endpoints,
            vdc.inter_vdc_cmd_endpoints,
            vdc.management_endpoints,
            vdc.secret_keys
        );
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update vdc failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn update(client: &mut ManagementClient, vdc: &Self) -> Result<bool> {
        let current_vdc = Self::get_by_id(client, &vdc.id)?;
        let mut state = false;
        if vdc.name != current_vdc.name
            || vdc.inter_vdc_endpoints != current_vdc.inter_vdc_endpoints
            || vdc.inter_vdc_cmd_endpoints != current_vdc.inter_vdc_cmd_endpoints
            || vdc.management_endpoints != current_vdc.management_endpoints
            || vdc.secret_keys != current_vdc.secret_keys
        {
            Self::update_vdc(client, vdc)?;
            state = true;
        }
        Ok(state)
    }

    // A deleted VDC cannot be added back
    pub(crate) fn delete(client: &mut ManagementClient, id: &str) -> Result<()> {
        let request_url = format!("{}object/vdcs/vdc/{}/deactivate", client.endpoint, id);
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        get_content_text(resp).with_context(|| "Failed to delete vdc")?;
        Ok(())
    }

    pub(crate) fn list(client: &mut ManagementClient) -> Result<Vec<Self>> {
        let request_url = format!("{}object/vdcs/vdc/list", client.endpoint);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to list VDCs")?;
        let resp: VdcList = serde_json::from_str(&text)
            .with_context(|| format!("Unable to deserialise VdcList. Body was: \"{}\"", text))?;
        Ok(resp.vdc)
    }
}

/// Vdc Keystore is to manage the certificates of a virtual data center (VDC)
#[derive(Builder, Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
pub struct VdcKeystore {
    /// Keystore certificate chain in PEM format. Updatable
    pub chain: String,
    /// The private key used to sign the certificate in PEM format. Updatable
    #[serde(default)]
    pub private_key: String,
}

impl VdcKeystore {
    pub(crate) fn get(client: &mut ManagementClient) -> Result<Self> {
        let request_url = format!("{}vdc/keystore", client.endpoint);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get vdc keystore")?;
        let resp: Self = serde_json::from_str(&text).with_context(|| {
            format!("Unable to deserialise VdcKeystore. Body was: \"{}\"", text)
        })?;
        Ok(resp)
    }

    pub(crate) fn update(client: &mut ManagementClient, keystore: &Self) -> Result<()> {
        let request_url = format!("{}vdc/keystore", client.endpoint);
        let body = format!(
            r#"{{"key_and_certificate":{{"private_key":"{}","certificate_chain":"{}"}}}}"#,
            keystore.private_key, keystore.chain
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/json")
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update vdc keystore failed: {}", resp.text()?);
        }
        Ok(())
    }
}

/// Storage pool is a logical construct that contains physical nodes.
#[derive(Builder, Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
#[builder(setter(skip))]
#[serde(rename_all = "camelCase", rename(serialize = "virtual_array_create"))]
pub struct StoragePool {
    /// Storage pool name. Required. Updatable
    #[builder(setter(into, skip = false))]
    pub name: String,
    /// Storage pool id
    pub id: String,
    /// Description. Default: "". Updatable
    #[builder(setter(into, skip = false), default)]
    pub description: String,
    /// Flag indicating that storage pool is protected. Default: false
    #[builder(setter(skip = false), default = false)]
    pub is_protected: bool,
    /// Flag indicating that cold storage encoding is enabled. Default: false
    #[builder(setter(skip = false), default = false)]
    pub is_cold_storage_enabled: bool,
    /// Number of Data Blocks in EC Scheme
    pub number_of_data_blocks: i64,
    /// Number of Code Blocks in EC Scheme
    pub number_of_code_blocks: i64,
    /// Threshold percent at which warning alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Default: 30. Updatable
    #[builder(setter(skip = false), default = 30)]
    pub warning_alert_at: i64,
    /// Threshold percent at which error alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Default: 20. Updatable
    #[builder(setter(skip = false), default = 20)]
    pub error_alert_at: i64,
    /// Threshold percent at which critical alert is raised. Valid values are from -1 to 100. Value of -1 means do not alert. Default: 15. Updatable
    #[builder(setter(skip = false), default = 15)]
    pub critical_alert_at: i64,
    /// Drive technology of VArray. Can be DRIVE_TECH_HDD. Required.
    // TODO: confirm the enum value for nvme
    #[builder(setter(into, skip = false))]
    pub label: String,
    /// Drive technology of VArray. Can be HDD or NVMe. Required.
    #[builder(setter(into, skip = false))]
    pub drive_technology: String,
    /// flag for status, -1 for null, 0 ~ 6 for value
    pub status: i64,
}

#[derive(PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
struct UpdateStoragePool {
    pub name: String,
    pub description: String,
    pub warning_alert_at: i64,
    pub error_alert_at: i64,
    pub critical_alert_at: i64,
    // just meet the need of the update payload
    // wont allow to change
    pub is_protected: bool,
}

impl From<StoragePool> for UpdateStoragePool {
    fn from(pool: StoragePool) -> Self {
        Self {
            name: pool.name,
            description: pool.description,
            warning_alert_at: pool.warning_alert_at,
            error_alert_at: pool.error_alert_at,
            critical_alert_at: pool.critical_alert_at,
            is_protected: pool.is_protected,
        }
    }
}

#[derive(Deserialize)]
struct StoragePoolList {
    varray: Vec<StoragePool>,
}

impl StoragePool {
    pub(crate) fn create(client: &mut ManagementClient, storage_pool: &Self) -> Result<Self> {
        let request_url = format!("{}vdc/data-services/varrays", client.endpoint);
        let body = quick_xml::se::to_string(&storage_pool)?;
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/xml")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to create storage pool")?;
        let resp: Self = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise StoragePool from create response. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp)
    }

    pub(crate) fn get(client: &mut ManagementClient, id: &str) -> Result<Self> {
        let request_url = format!("{}vdc/data-services/varrays/{}", client.endpoint, id);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get storage pool")?;
        let resp: Self = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise StoragePool from get response. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp)
    }

    pub(crate) fn update_storage_pool(
        client: &mut ManagementClient,
        storage_pool: &Self,
    ) -> Result<()> {
        let request_url = format!(
            "{}vdc/data-services/varrays/{}",
            client.endpoint, storage_pool.id
        );
        let update_storage_pool = UpdateStoragePool::from(storage_pool.to_owned());
        let body = serde_json::to_string(&update_storage_pool)?;
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/json")
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update storage pool failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn update(client: &mut ManagementClient, storage_pool: &Self) -> Result<bool> {
        let current_storage_pool = Self::get(client, &storage_pool.id)?;
        let mut updated_storage_pool = UpdateStoragePool::from(storage_pool.clone());
        let current_updated_storege_pool = UpdateStoragePool::from(current_storage_pool);
        // prevent is_protected from being updated
        // changing is_protected seems to be destructive
        updated_storage_pool.is_protected = current_updated_storege_pool.is_protected;
        if current_updated_storege_pool != updated_storage_pool {
            Self::update_storage_pool(client, storage_pool)?;
            Ok(true)
        } else {
            Ok(false)
        }
    }

    pub(crate) fn list(client: &mut ManagementClient) -> Result<Vec<Self>> {
        let request_url = format!("{}vdc/data-services/varrays", client.endpoint);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to list storage pools")?;
        let resp: StoragePoolList = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise StoragePoolList. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp.varray)
    }
}
