//
// Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//

//! Define the replication details.
//!
use crate::client::{ManagementClient, AUTH_HEADER_KEY};
use crate::response::get_content_text;
use anyhow::{Context as _, Result};
use derive_builder::Builder;
use reqwest::header::{ACCEPT, CONTENT_TYPE};
use serde::{Deserialize, Serialize};
use serde_aux::field_attributes::deserialize_default_from_null;

#[derive(Clone, Default, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct VarrayMapping {
    /// Virtual data center id
    pub name: String,
    /// Storage pool id
    pub value: String,
    /// is replication target
    pub is_replication_target: bool,
}

/// Storage pool is a logical construct that contains physical nodes.
#[derive(Builder, Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
#[serde(
    rename_all = "camelCase",
    rename(serialize = "data_service_vpool_create")
)]
#[builder(setter(skip))]
pub struct ReplicationGroup {
    /// Indicates whether the resource is global.
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub global: bool,
    /// Indicates whether the resource is remote.
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub remote: bool,
    // TODO:
    // #[serde(deserialize_with = "deserialize_default_from_null")]
    // pub vdc: String,
    /// Varray mappings. Required
    #[builder(setter(skip = false))]
    #[serde(rename(serialize = "zone_mappings", deserialize = "varrayMappings"))]
    pub varray_mappings: Vec<VarrayMapping>,
    /// Unique name identifying this classification of replication group. Required. Updatable
    #[builder(setter(into))]
    pub name: String,
    /// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.
    pub id: String,
    // TODO:
    // Hyperlink to the details for this resource
    // pub link: Link,
    /// Timestamp that shows when this resource was created in ECS
    #[serde(rename = "creation_time")]
    pub creation_time: i64,
    /// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.
    pub inactive: bool,
    /// Indicated whether the resource is an internal resource
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub internal: bool,
    /// Description of the replication group. Default: "". Updatable
    #[builder(setter(into), default)]
    pub description: String,
    /// Parameter to check if the Vpool can access all Namespace. Default: true. Updatable
    #[builder(setter(skip = false), default = true)]
    pub is_allow_all_namespaces: bool,
    /// Parameter to check if the rebalancing is enabled. Default: false. Updatable
    #[serde(rename = "enable_rebalancing")]
    #[builder(setter(skip = false), default = false)]
    pub enable_rebalancing: bool,
    /// Parameter to check if to use replication targets. Default: false
    #[builder(setter(skip = false), default = false)]
    pub use_replication_target: bool,
    /// set full replication flag. Default: false
    #[builder(setter(skip = false), default = false)]
    pub is_full_rep: bool,
}

#[derive(Deserialize)]
struct ReplicationGroupList {
    data_service_vpool: Vec<ReplicationGroup>,
}

impl ReplicationGroup {
    pub(crate) fn create(client: &mut ManagementClient, replication_group: &Self) -> Result<()> {
        let request_url = format!("{}vdc/data-service/vpools", client.endpoint);
        let body = quick_xml::se::to_string(replication_group)?;
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/xml")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to create replication group")?;
        Ok(())
    }

    pub(crate) fn get(client: &mut ManagementClient, id: &str) -> Result<Self> {
        let request_url = format!("{}vdc/data-service/vpools/{}", client.endpoint, id);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get replication group")?;
        let resp: Self = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise ReplicationGroup. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp)
    }

    pub(crate) fn update_replication_group(
        client: &mut ManagementClient,
        replication_group: &Self,
        current_replication_group: &Self,
    ) -> Result<()> {
        let request_url = format!(
            "{}vdc/data-service/vpools/{}",
            client.endpoint, replication_group.id
        );
        let name = if replication_group.name != current_replication_group.name {
            format!(r#","name":"{}""#, replication_group.name)
        } else {
            "".to_string()
        };
        let body = format!(
            r#"{{"description":"{}","enable_rebalancing":{},"allowAllNamespaces":{}{}}}"#,
            replication_group.description,
            replication_group.enable_rebalancing,
            replication_group.is_allow_all_namespaces,
            name
        );
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        get_content_text(resp).with_context(|| "Failed to update replication group")?;
        Ok(())
    }

    // TODO: addvarrays && removevarrays from replication group.
    // A removed array cannot be added back to the replication group
    pub(crate) fn update(client: &mut ManagementClient, replication_group: &Self) -> Result<bool> {
        let current_replication_group = Self::get(client, &replication_group.id)?;
        let mut updated = false;

        if replication_group.name != current_replication_group.name
            || replication_group.description != current_replication_group.description
            || replication_group.enable_rebalancing != current_replication_group.enable_rebalancing
            || replication_group.is_allow_all_namespaces
                != current_replication_group.is_allow_all_namespaces
        {
            updated = true;
            Self::update_replication_group(client, replication_group, &current_replication_group)?;
        }
        Ok(updated)
    }

    pub(crate) fn list(client: &mut ManagementClient) -> Result<Vec<Self>> {
        let request_url = format!("{}vdc/data-service/vpools", client.endpoint);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to list replication groups")?;
        let resp: ReplicationGroupList = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise ReplicationGroupList. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp.data_service_vpool)
    }
}
