//! Define the tenancy details.
//!
use crate::client::{ManagementClient, AUTH_HEADER_KEY};
use crate::response::get_content_text;
use anyhow::{bail, Context as _, Result};
use derive_builder::Builder;
use reqwest::header::{ACCEPT, CONTENT_TYPE};
use serde::{Deserialize, Serialize};
use serde_aux::field_attributes::{deserialize_bool_from_anything, deserialize_default_from_null};

#[derive(Clone, Default, Debug, Deserialize, Serialize)]
pub struct Link {
    pub rel: String,
    pub href: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct RetionClass {
    /// Name of the retention class
    pub name: String,
    /// Period of the retention class in seconds
    pub period: u64,
}

#[derive(Clone, Default, Debug, Deserialize, Serialize)]
pub struct RetionClasses {
    /// Retention class, add and update only
    pub retention_class: Vec<RetionClass>,
}

/// ECS supports access by multiple tenants, where each tenant is defined by a namespace.
#[derive(Builder, Clone, Debug, Default, Deserialize, Serialize)]
#[builder(setter(skip))]
#[serde(rename(serialize = "namespace_create"))]
pub struct Namespace {
    /// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier. Non-updateable
    #[builder(setter(into))]
    #[serde(rename(serialize = "namespace"))]
    pub name: String,
    /// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time
    pub id: String,
    /// Indicates whether the resource is global
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub global: bool,
    /// Indicates whether the resource is remote
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub remote: bool,
    // pub vdc: String,
    /// Hyperlink to the details for this resource
    pub link: Link,
    /// Timestamp that shows when this resource was created in ECS
    pub creation_time: u64,
    /// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database
    pub inactive: bool,
    /// Indicated whether the resource is an internal resource
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub internal: bool,
    /// Default replication group identifier for this tenant when creating buckets
    #[builder(setter(into, skip = false), default)]
    pub default_data_services_vpool: String,
    /// List of replication group that are allowed access to namespace
    pub allowed_vpools_list: Vec<String>,
    /// List of replication group that are not allowed access to namespace
    pub disallowed_vpools_list: Vec<String>,
    /// Comma separated list of namespace admins
    pub namespace_admins: String,
    pub user_mapping: Vec<String>,
    /// encryption status of the namesapce
    #[builder(setter(skip = false), default = "false")]
    #[serde(deserialize_with = "deserialize_bool_from_anything")]
    pub is_encryption_enabled: bool,
    /// Default bucket quota size.
    #[builder(setter(skip = false), default = -1)]
    pub default_bucket_block_size: i64,
    /// List of groups from AD Server
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub external_group_admins: String,
    /// Namespace isStaleAllowed flag
    pub is_stale_allowed: bool,
    /// Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Optional.
    #[builder(setter(skip = false), default = "false")]
    pub is_object_lock_with_ado_allowed: bool,
    /// Namespace isComplianceEnabled flag
    #[builder(setter(skip = false), default = "false")]
    pub is_compliance_enabled: bool,
    /// Notification Size in GB
    #[serde(rename = "notificationSize")]
    #[builder(setter(skip = false), default = -1)]
    pub notification_size: i64,
    /// Block Size in GB
    #[serde(rename = "blockSize")]
    #[builder(setter(skip = false), default = -1)]
    pub block_size: i64,
    /// Notification Size in Count
    #[serde(rename = "notificationSizeInCount")]
    #[builder(setter(skip = false), default = -1)]
    pub notification_size_in_count: i64,
    /// Block Size in Count
    #[serde(rename = "blockSizeInCount")]
    #[builder(setter(skip = false), default = -1)]
    pub block_size_in_count: i64,
    /// Default bucket audit delete expiration
    #[serde(deserialize_with = "deserialize_default_from_null")]
    pub default_audit_delete_expiration: i64,
    /// retention classes
    #[builder(setter(skip = false), default)]
    pub retention_classes: RetionClasses,
    /// root user name
    pub root_user_name: String,
    /// root user password
    pub root_user_password: String,
}

fn below_zero(val: &i64) -> bool {
    *val < 0
}

#[derive(Debug, Serialize)]
#[serde(
    rename_all = "camelCase",
    rename(serialize = "namespace_quota_details")
)]
struct UpdateNamespaceQuota {
    #[serde(skip_serializing_if = "below_zero")]
    pub block_size: i64,
    #[serde(skip_serializing_if = "below_zero")]
    pub notification_size: i64,
    #[serde(skip_serializing_if = "below_zero")]
    pub block_size_in_count: i64,
    #[serde(skip_serializing_if = "below_zero")]
    pub notification_size_in_count: i64,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct ListNamespacesResponse {
    #[serde(rename = "namespace")]
    pub namespace: Vec<Namespace>,
    pub max_namespaces: Option<u32>,
    pub next_marker: Option<String>,
    pub filter: String,
    pub next_page_link: Option<String>,
}

impl Namespace {
    pub(crate) fn create(
        client: &mut ManagementClient,
        namespace: &Namespace,
    ) -> Result<Namespace> {
        let request_url = format!("{}object/namespaces/namespace", client.endpoint);
        let body = quick_xml::se::to_string(&namespace)?;
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .header(CONTENT_TYPE, "application/xml")
            .body(body)
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to create namespace")?;
        let resp: Namespace = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise Namespace from creation response payload. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp)
    }

    pub(crate) fn get(client: &mut ManagementClient, id: &str) -> Result<Namespace> {
        let request_url = format!("{}object/namespaces/namespace/{}", client.endpoint, id);
        let resp = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        let text = get_content_text(resp).with_context(|| "Failed to get namespace")?;
        let resp: Namespace = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise Namespace from read response payload. Body was: \"{}\"",
                text
            )
        })?;
        Ok(resp)
    }

    pub(crate) fn update_quota(
        client: &mut ManagementClient,
        id: &str,
        block_size: i64,
        notification_size: i64,
        block_size_in_count: i64,
        notification_size_in_count: i64,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/namespaces/namespace/{}/quota",
            client.endpoint, id
        );
        let update_quota = UpdateNamespaceQuota {
            block_size,
            notification_size,
            block_size_in_count,
            notification_size_in_count,
        };
        let body = quick_xml::se::to_string(&update_quota)?;
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/xml")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update namespace quota failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn delete_quota(client: &mut ManagementClient, id: &str) -> Result<()> {
        let request_url = format!(
            "{}object/namespaces/namespace/{}/quota",
            client.endpoint, id
        );
        let resp = client
            .http_client
            .delete(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        if !resp.status().is_success() {
            bail!("Delete namespace quota failed: {}", resp.text()?);
        }
        Ok(())
    }

    // TODO: update namespace
    pub(crate) fn update_namespace(
        client: &mut ManagementClient,
        namespace: Namespace,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/namespaces/namespace/{}",
            client.endpoint, namespace.id
        );
        let body = quick_xml::se::to_string(&namespace)?;
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update namespace failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn create_retention_class(
        client: &mut ManagementClient,
        id: &str,
        name: String,
        period: u64,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/namespaces/namespace/{}/retention",
            client.endpoint, id
        );
        let retention_class = RetionClass { name, period };
        let body = serde_json::to_string(&retention_class)?;
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Create retention class failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn update_retention_class(
        client: &mut ManagementClient,
        id: &str,
        name: String,
        period: u64,
    ) -> Result<()> {
        let request_url = format!(
            "{}object/namespaces/namespace/{}/retention/{}",
            client.endpoint, id, name
        );
        let body = format!(r#"{{"period":{}}}"#, period);
        let resp = client
            .http_client
            .put(request_url)
            .header(ACCEPT, "application/json")
            .header(CONTENT_TYPE, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .body(body)
            .send()?;
        if !resp.status().is_success() {
            bail!("Update retention class failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn update(
        client: &mut ManagementClient,
        namespace: Self,
        current_namespace: Option<Self>,
    ) -> Result<Namespace> {
        let current_namespace = if let Some(namespace) = current_namespace {
            namespace
        } else {
            Self::get(client, &namespace.id)?
        };

        if namespace.block_size != current_namespace.block_size
            || namespace.notification_size != current_namespace.notification_size
            || namespace.block_size_in_count != current_namespace.block_size_in_count
            || namespace.notification_size_in_count != current_namespace.notification_size_in_count
        {
            if namespace.block_size == -1
                && namespace.notification_size == -1
                && namespace.block_size_in_count == -1
                && namespace.notification_size_in_count == -1
            {
                Self::delete_quota(client, &current_namespace.id)?;
            } else {
                Self::update_quota(
                    client,
                    &current_namespace.id,
                    namespace.block_size,
                    namespace.notification_size,
                    namespace.block_size_in_count,
                    namespace.notification_size_in_count,
                )?;
            }
        }
        for class in &namespace.retention_classes.retention_class {
            let classes = &current_namespace.retention_classes.retention_class;
            if classes.iter().any(|c| c.name == class.name) {
                Self::update_retention_class(
                    client,
                    &current_namespace.id,
                    class.name.clone(),
                    class.period,
                )?;
            } else {
                Self::create_retention_class(
                    client,
                    &current_namespace.id,
                    class.name.clone(),
                    class.period,
                )?;
            }
        }

        Self::get(client, &current_namespace.id)
    }

    pub(crate) fn delete(client: &mut ManagementClient, id: &str) -> Result<()> {
        let request_url = format!(
            "{}object/namespaces/namespace/{}/deactivate",
            client.endpoint, id
        );
        let resp = client
            .http_client
            .post(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap())
            .send()?;
        if !resp.status().is_success() {
            bail!("Delete namespace failed: {}", resp.text()?);
        }
        Ok(())
    }

    pub(crate) fn list(client: &mut ManagementClient, name_prefix: &str) -> Result<Vec<Namespace>> {
        let request_url = format!("{}object/namespaces", client.endpoint);
        let mut req = client
            .http_client
            .get(request_url)
            .header(ACCEPT, "application/json")
            .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap());
        if !name_prefix.is_empty() {
            req = req.query(&[("name", name_prefix)]);
        }
        let response = req.send()?;
        let text = get_content_text(response)?;
        // sample:
        // {"namespace":[{"global":null,"remote":null,"vdc":null,"name":"ns1","id":"ns1","link":{"rel":"self","href":"/object/namespaces/namespace/ns1"},
        // "creation_time":1752815009275,"inactive":false,"internal":null,"default_data_services_vpool":"urn:storageos:ReplicationGroupInfo:0e953ad1-94a5-4eb1-825a-d58d29e85434:global",
        // "allowed_vpools_list":[],"disallowed_vpools_list":[],"namespace_admins":"root","user_mapping":[],"is_encryption_enabled":"false",
        // "default_bucket_block_size":-1,"external_group_admins":null,"is_stale_allowed":false,"is_object_lock_with_ado_allowed":false,"is_compliance_enabled":false,
        // "notificationSize":-1,"blockSize":-1,"notificationSizeInCount":-1,"blockSizeInCount":-1,"default_audit_delete_expiration":null,"retention_classes":{"retention_class":[]},
        // "root_user_password":"","root_user_name":"root@@ns1"}],"MaxNamespaces":null,"NextMarker":null,"Filter":"name=*","NextPageLink":null}
        let mut resp: ListNamespacesResponse = serde_json::from_str(&text).with_context(|| {
            format!(
                "Unable to deserialise ListNamespacesResponse. Body was: \"{}\"",
                text
            )
        })?;
        let mut namespaces: Vec<Namespace> = vec![];
        namespaces.extend(resp.namespace);
        while let Some(marker) = resp.next_marker {
            let request_url = format!("{}object/namespaces?marker={}", client.endpoint, marker);
            let mut req = client
                .http_client
                .get(request_url)
                .header(ACCEPT, "application/json")
                .header(AUTH_HEADER_KEY, client.access_token.as_ref().unwrap());
            if !name_prefix.is_empty() {
                req = req.query(&[("name", name_prefix)]);
            }
            let response = req.send()?;
            let text = get_content_text(response)?;
            resp = serde_json::from_str(&text).with_context(|| {
                format!(
                    "Unable to deserialise ListNamespacesResponse. Body was: \"{}\"",
                    text
                )
            })?;
            namespaces.extend(resp.namespace);
        }
        Ok(namespaces)
    }
}
